table 'Canada LFS Monthly'
	lineageTag: 739b5b55-0d8b-492b-9c69-a3f6137415a1

	column ReferenceMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7384cc3-45e3-4c66-ad22-d8e41f4c13ef
		summarizeBy: none
		sourceColumn: ReferenceMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Country
		dataType: string
		lineageTag: 0874981e-97be-48d6-a5ff-dba17cca242d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 2c325caa-2251-4133-a412-256d88933542
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column ChildStatus
		dataType: string
		lineageTag: c1af4b91-b837-4d6a-8209-7cf1b2e95bf8
		summarizeBy: none
		sourceColumn: ChildStatus

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: c5d53756-e655-4b73-b818-8fca2db2c318
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: c8239581-ef67-4568-8b09-9b388dcccd36
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Canada LFS Monthly' = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100397-eng.zip"),
				    ZipFiles = Unzip(Source),
				    Content = ZipFiles{0}[Content],
				    ImportedCSV = Csv.Document(Content, [Delimiter = ",", Columns = 19, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(ImportedCSV, [PromoteAllScalars = true]),
				    ChangedType =
				        Table.TransformColumnTypes(
				            PromotedHeaders,
				            {
				                {"REF_DATE", type date},
				                {"GEO", type text},
				                {"Labour force characteristics", type text},
				                {"Age", type text},
				                {"Gender", type text},
				                {"Family type", type text},
				                {"Family age composition", type text},
				                {"VALUE", type number}
				            }
				        ),
				    FilteredRows =
				        Table.SelectRows(
				            ChangedType,
				            each
				                [GEO] = "Canada"
				                    and [Age] = "25 to 54 years"
				                    and List.Contains({"Women+", "Men+"}, [Gender])
				                    and [Family type] = "Total, all reference persons and their spouses"
				                    and List.Contains(
				                        {"Youngest child 0 to 5 years", "Without children less than 18 years"},
				                        [Family age composition]
				                    )
				                    and List.Contains(
				                        {"Participation rate", "Employment rate", "Unemployment rate"},
				                        [Labour force characteristics]
				                    )
				        ),
				    SelectedColumns =
				        Table.SelectColumns(
				            FilteredRows,
				            {
				                "REF_DATE",
				                "Gender",
				                "Family age composition",
				                "Labour force characteristics",
				                "VALUE"
				            }
				        ),
				    WithCountry = Table.AddColumn(SelectedColumns, "Country", each "Canada", type text),
				    WithSex =
				        Table.AddColumn(
				            WithCountry,
				            "Sex",
				            each if [Gender] = "Women+" then "Women" else "Men",
				            type text
				        ),
				    WithChildStatus =
				        Table.AddColumn(
				            WithSex,
				            "ChildStatus",
				            each
				                if [Family age composition] = "Youngest child 0 to 5 years" then
				                    "Youngest child 0 to 5 years"
				                else
				                    "No child under 18",
				            type text
				        ),
				    RenamedColumns =
				        Table.RenameColumns(
				            WithChildStatus,
				            {
				                {"REF_DATE", "ReferenceMonth"},
				                {"Labour force characteristics", "Indicator"},
				                {"VALUE", "Value"}
				            }
				        ),
				    Grouped =
				        Table.Group(
				            RenamedColumns,
				            {"ReferenceMonth", "Country", "Sex", "ChildStatus", "Indicator"},
				            {{"Value", each List.Max(List.RemoveNulls([Value])), type nullable number}}
				        ),
				    Sorted =
				        Table.Sort(
				            Grouped,
				            {
				                {"ReferenceMonth", Order.Ascending},
				                {"Sex", Order.Ascending},
				                {"ChildStatus", Order.Ascending},
				                {"Indicator", Order.Ascending}
				            }
				        )
				in
				    Sorted

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

