table 'Inflation Comparison'
	lineageTag: 1618318c-b3b5-483e-9013-1270fdbc5476

	measure 'CPI Index' =
			
			AVERAGE ( 'Inflation Comparison'[Value] )
		formatString: 0.0
		lineageTag: 7889777d-2df0-49f6-84bd-a64b19f5a894

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI YoY %' =
			
			VAR CurrentIndex =
			    [CPI Index]
			
			VAR PriorYearIndex =
			    CALCULATE (
			        [CPI Index],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			
			RETURN
			    DIVIDE ( CurrentIndex - PriorYearIndex, PriorYearIndex )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 26b1d75a-e285-49ef-a1a5-a2e03f7b5292

	measure 'CPI MoM %' =
			
			VAR CurrentIndex =
			    [CPI Index]
			
			VAR PriorMonthIndex =
			    CALCULATE (
			        [CPI Index],
			        DATEADD ( 'Date'[Date], -1, MONTH )
			    )
			
			RETURN
			    DIVIDE ( CurrentIndex - PriorMonthIndex, PriorMonthIndex )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d278cb4f-59a1-4f18-9849-36b2de976a35

	column ReferenceMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 30ae2a8b-4c3e-439c-ac18-f3877462ce65
		summarizeBy: none
		sourceColumn: ReferenceMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Country
		dataType: string
		lineageTag: 49d7ddd7-056e-4504-b9e7-35dc5c074c47
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Series
		dataType: string
		lineageTag: 648199eb-a2a2-40fc-aa1f-4a9d4022ee2d
		summarizeBy: none
		sourceColumn: Series

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 77b06170-a24d-4e1c-8555-89cb00f7b886
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Inflation Comparison' = m
		mode: import
		source =
				let
				    StartYear = 2010,
				    EndYear = Date.Year(DateTime.Date(DateTime.LocalNow())),
				    BlsSeries =
				        #table(
				            {"SeriesID", "Series"},
				            {
				                {"CUUR0000SEEB03", "Child care services"},
				                {"CUUR0000SA0", "All-items"}
				            }
				        ),
				    GetBlsSeries =
				        (SeriesID as text, SeriesLabel as text) as table =>
				        let
				            Response =
				                Json.Document(
				                    Web.Contents(
				                        "https://api.bls.gov",
				                        [
				                            RelativePath = "publicAPI/v2/timeseries/data/" & SeriesID,
				                            Query = [
				                                startyear = Text.From(StartYear),
				                                endyear = Text.From(EndYear)
				                            ],
				                            Timeout = #duration(0, 0, 2, 0)
				                        ]
				                    )
				                ),
				            Data = Response[Results][series]{0}[data],
				            DataTable = Table.FromRecords(Data),
				            FilteredRows =
				                Table.SelectRows(
				                    DataTable,
				                    each [period] <> "M13" and [value] <> null and [value] <> "-"
				                ),
				            WithReferenceMonth =
				                Table.AddColumn(
				                    FilteredRows,
				                    "ReferenceMonth",
				                    each #date(Number.FromText([year]), Number.FromText(Text.Range([period], 1, 2)), 1),
				                    type date
				                ),
				            WithValue =
				                Table.TransformColumnTypes(
				                    WithReferenceMonth,
				                    {{"value", type number}}
				                ),
				            WithCountry = Table.AddColumn(WithValue, "Country", each "United States", type text),
				            WithSeries = Table.AddColumn(WithCountry, "Series", each SeriesLabel, type text),
				            SelectedColumns =
				                Table.SelectColumns(
				                    WithSeries,
				                    {"ReferenceMonth", "Country", "Series", "value"}
				                ),
				            RenamedColumns = Table.RenameColumns(SelectedColumns, {{"value", "Value"}})
				        in
				            RenamedColumns,
				    BlsTables =
				        List.Transform(
				            Table.ToRecords(BlsSeries),
				            each GetBlsSeries(_[SeriesID], _[Series])
				        ),
				    BlsCombined = Table.Combine(BlsTables),
				    CanadaSource = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/18100004-eng.zip"),
				    CanadaZipFiles = Unzip(CanadaSource),
				    CanadaContent = CanadaZipFiles{0}[Content],
				    CanadaCSV = Csv.Document(CanadaContent, [Delimiter = ",", Columns = 15, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    CanadaHeaders = Table.PromoteHeaders(CanadaCSV, [PromoteAllScalars = true]),
				    CanadaTyped =
				        Table.TransformColumnTypes(
				            CanadaHeaders,
				            {
				                {"REF_DATE", type date},
				                {"GEO", type text},
				                {"Products and product groups", type text},
				                {"VALUE", type number}
				            }
				        ),
				    CanadaFiltered =
				        Table.SelectRows(
				            CanadaTyped,
				            each
				                [REF_DATE] >= #date(StartYear, 1, 1)
				                    and [GEO] = "Canada"
				                    and List.Contains({"Child care services", "All-items"}, [Products and product groups])
				        ),
				    CanadaSelected =
				        Table.SelectColumns(
				            CanadaFiltered,
				            {"REF_DATE", "Products and product groups", "VALUE"}
				        ),
				    CanadaRenamed =
				        Table.RenameColumns(
				            CanadaSelected,
				            {
				                {"REF_DATE", "ReferenceMonth"},
				                {"Products and product groups", "Series"},
				                {"VALUE", "Value"}
				            }
				        ),
				    CanadaWithCountry = Table.AddColumn(CanadaRenamed, "Country", each "Canada", type text),
				    CanadaFinal =
				        Table.SelectColumns(
				            CanadaWithCountry,
				            {"ReferenceMonth", "Country", "Series", "Value"}
				        ),
				    Combined = Table.Combine({CanadaFinal, BlsCombined}),
				    Grouped =
				        Table.Group(
				            Combined,
				            {"ReferenceMonth", "Country", "Series"},
				            {{"Value", each List.Max(List.RemoveNulls([Value])), type nullable number}}
				        ),
				    Sorted =
				        Table.Sort(
				            Grouped,
				            {
				                {"ReferenceMonth", Order.Ascending},
				                {"Country", Order.Ascending},
				                {"Series", Order.Ascending}
				            }
				        )
				in
				    Sorted

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

