table 'CSD Indicators'
	lineageTag: f23d2e90-58c4-486d-a307-519299415155

	column 'CSD Number'
		dataType: string
		isHidden
		lineageTag: 9fd70ad5-430d-4e5f-86f9-3f1d0f9e5281
		summarizeBy: none
		sourceColumn: CSD Number

	column 'Province Code'
		dataType: int64
		isHidden
		lineageTag: cba5c33a-dc25-4c8e-aad2-713acfd20daa
		summarizeBy: none
		sourceColumn: Province Code

	column Indicator
		dataType: string
		lineageTag: 3000a5a1-0617-4d69-8df0-56110df73d31
		summarizeBy: none
		sourceColumn: Indicator

	column 'Indicator Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f216b14-a6d3-4578-aa52-68a7eef99b20
		summarizeBy: none
		sourceColumn: Indicator Sort

	column 'Children Count'
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: e6947bcd-b77e-4b22-a89b-7d015edda6a0
		summarizeBy: sum
		sourceColumn: Children Count

	column Percent
		dataType: decimal
		isHidden
		formatString: 0.0
		lineageTag: 88c26924-c378-4b92-a38e-d941d61166ee
		summarizeBy: none
		sourceColumn: Percent

	column 'Value Status'
		dataType: string
		lineageTag: 4ec7fa1d-ee36-47a9-80cb-8051c5fcb576
		summarizeBy: none
		sourceColumn: Value Status

	partition 'CSD Indicators' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(#"DataFolder" & "csd_indicators.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Blank Values As Null" = Table.ReplaceValue(#"Promoted Headers", "", null, Replacer.ReplaceValue, Table.ColumnNames(#"Promoted Headers")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Blank Values As Null", {{"CSD Number", type text}, {"Province Code", Int64.Type}, {"Indicator", type text}, {"Indicator Sort", Int64.Type}, {"Children Count", Int64.Type}, {"Percent", type number}, {"Value Status", type text}}, "en-CA")
				in
				    #"Changed Type"

