table 'CSD Indicators'

	column 'CSD Number'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: CSD Number

	column 'Province Code'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Province Code

	column Indicator
		dataType: string
		summarizeBy: none
		sourceColumn: Indicator

	column 'Indicator Sort'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: Indicator Sort

	column 'Children Count'
		dataType: int64
		formatString: #,##0
		isHidden
		summarizeBy: sum
		sourceColumn: Children Count

	column Percent
		dataType: decimal
		formatString: 0.0
		isHidden
		summarizeBy: none
		sourceColumn: Percent

	column 'Value Status'
		dataType: string
		summarizeBy: none
		sourceColumn: Value Status


	partition 'CSD Indicators' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(#"DataFolder" & "csd_indicators.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Blank Values As Null" = Table.ReplaceValue(#"Promoted Headers", "", null, Replacer.ReplaceValue, Table.ColumnNames(#"Promoted Headers")),
			    #"Changed Type" = Table.TransformColumnTypes(#"Blank Values As Null", {{"CSD Number", type text}, {"Province Code", Int64.Type}, {"Indicator", type text}, {"Indicator Sort", Int64.Type}, {"Children Count", Int64.Type}, {"Percent", type number}, {"Value Status", type text}}, "en-CA")
			in
			    #"Changed Type"
