table Indicator

	column Indicator
		dataType: string
		summarizeBy: none
		sourceColumn: Indicator

	column 'Indicator Short Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Indicator Short Name

	column 'Indicator Description'
		dataType: string
		summarizeBy: none
		sourceColumn: Indicator Description

	column 'Indicator Sort'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: Indicator Sort


	partition Indicator = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(#"DataFolder" & "indicator.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Blank Values As Null" = Table.ReplaceValue(#"Promoted Headers", "", null, Replacer.ReplaceValue, Table.ColumnNames(#"Promoted Headers")),
			    #"Changed Type" = Table.TransformColumnTypes(#"Blank Values As Null", {{"Indicator", type text}, {"Indicator Short Name", type text}, {"Indicator Description", type text}, {"Indicator Sort", Int64.Type}}, "en-CA")
			in
			    #"Changed Type"
