table 'MIZ Summary'
	lineageTag: 14d38469-30ee-4860-ba3b-bb284f96144b

	measure 'MIZ Children 0 to 5' =
			SUMX (
			    SUMMARIZE (
			        'MIZ Summary',
			        'MIZ Summary'[MIZ Analysis Label],
			        "Children", MAX ( 'MIZ Summary'[Children Aged 0 to 5] )
			    ),
			    [Children]
			)
		formatString: #,##0
		displayFolder: MIZ
		lineageTag: 60f9b076-85c8-4987-b068-5f8451bd1833

	measure 'MIZ Indicator Children' = SUM ( 'MIZ Summary'[Children Count] )
		formatString: #,##0
		displayFolder: MIZ
		lineageTag: 67baebc5-f3af-467c-ba49-f25c7ed437e0

	measure 'MIZ Indicator Rate' = DIVIDE ( [MIZ Indicator Children], [MIZ Children 0 to 5] )
		formatString: 0.0%
		displayFolder: MIZ
		lineageTag: eff809df-222b-4e6a-acbe-478db4bf9973

	column 'MIZ Identifier'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1100cd1b-badb-46b4-aa79-194b4718960f
		summarizeBy: none
		sourceColumn: MIZ Identifier

	column 'MIZ Analysis Label'
		dataType: string
		lineageTag: 07e934f5-461b-4430-9c7f-b1ecfc77f02b
		summarizeBy: none
		sourceColumn: MIZ Analysis Label
		sortByColumn: 'MIZ Identifier'

	column 'MIZ Label'
		dataType: string
		lineageTag: 243a4136-73c2-4a10-90fd-b1b79ff1ab74
		summarizeBy: none
		sourceColumn: MIZ Label

	column 'Geography Type'
		dataType: string
		lineageTag: d7f92462-bec3-4058-8802-e8f23942fa37
		summarizeBy: none
		sourceColumn: Geography Type

	column Indicator
		dataType: string
		lineageTag: 312ad0ff-61dd-421e-a2ea-2913f9c19572
		summarizeBy: none
		sourceColumn: Indicator

	column 'Indicator Short Name'
		dataType: string
		lineageTag: 07587428-7824-45cd-aab5-ada657507e38
		summarizeBy: none
		sourceColumn: Indicator Short Name
		sortByColumn: 'Indicator Sort'

	column 'Indicator Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 29a2201d-2137-4a8d-b834-1bcbc18792e9
		summarizeBy: none
		sourceColumn: Indicator Sort

	column 'Children Aged 0 to 5'
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: b1c95a9b-9d36-4d92-9deb-f70d91d370ab
		summarizeBy: sum
		sourceColumn: Children Aged 0 to 5

	column 'Children Count'
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: 49fb81a5-814f-4839-8333-507a718507ed
		summarizeBy: sum
		sourceColumn: Children Count

	column Percent
		dataType: decimal
		isHidden
		formatString: 0.0%
		lineageTag: 599e7a1a-e7e2-429e-a860-3701f6164322
		summarizeBy: none
		sourceColumn: Percent

	partition 'MIZ Summary' = m
		mode: import
		source =
				let
				    Source = CensusChildrenData,
				    #"Filtered Rows" = Table.SelectRows(Source, each [Record Type] = "MIZ Summary"),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Rows", {"MIZ Identifier", "MIZ Analysis Label", "MIZ Label", "Geography Type", "Indicator", "Indicator Short Name", "Indicator Sort", "Children Aged 0 to 5", "Children Count", "Percent"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Selected Columns", {{"MIZ Identifier", Int64.Type}, {"MIZ Analysis Label", type text}, {"MIZ Label", type text}, {"Geography Type", type text}, {"Indicator", type text}, {"Indicator Short Name", type text}, {"Indicator Sort", Int64.Type}, {"Children Aged 0 to 5", Int64.Type}, {"Children Count", Int64.Type}, {"Percent", type number}}, "en-CA")
				in
				    #"Changed Type"

