table Notes
	lineageTag: 6b6900e0-c6d8-4a43-aac6-f8403ffef5d6

	column 'Note Number'
		dataType: int64
		formatString: 0
		lineageTag: bf62e40a-5ac2-41f2-a91f-639cb6b03b55
		summarizeBy: none
		sourceColumn: Note Number

	column Note
		dataType: string
		lineageTag: bbd366dc-3ba2-4164-ad5a-609be9df67bd
		summarizeBy: none
		sourceColumn: Note

	partition Notes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(#"DataFolder" & "notes.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Blank Values As Null" = Table.ReplaceValue(#"Promoted Headers", "", null, Replacer.ReplaceValue, Table.ColumnNames(#"Promoted Headers")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Blank Values As Null", {{"Note Number", Int64.Type}, {"Note", type text}}, "en-CA")
				in
				    #"Changed Type"

