table Notes

	column 'Note Number'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Note Number

	column Note
		dataType: string
		summarizeBy: none
		sourceColumn: Note


	partition Notes = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(#"DataFolder" & "notes.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Blank Values As Null" = Table.ReplaceValue(#"Promoted Headers", "", null, Replacer.ReplaceValue, Table.ColumnNames(#"Promoted Headers")),
			    #"Changed Type" = Table.TransformColumnTypes(#"Blank Values As Null", {{"Note Number", Int64.Type}, {"Note", type text}}, "en-CA")
			in
			    #"Changed Type"
