table Notes
	lineageTag: 6b6900e0-c6d8-4a43-aac6-f8403ffef5d6

	column 'Note Number'
		dataType: int64
		formatString: 0
		lineageTag: bf62e40a-5ac2-41f2-a91f-639cb6b03b55
		summarizeBy: none
		sourceColumn: Note Number

	column Note
		dataType: string
		lineageTag: bbd366dc-3ba2-4164-ad5a-609be9df67bd
		summarizeBy: none
		sourceColumn: Note

	partition Notes = m
		mode: import
		source =
				let
				    Source = CensusChildrenData,
				    #"Filtered Rows" = Table.SelectRows(Source, each [Record Type] = "Notes"),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Rows", {"Note Number", "Note"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Selected Columns", {{"Note Number", Int64.Type}, {"Note", type text}}, "en-CA")
				in
				    #"Changed Type"

