table 'Province Indicators'
	lineageTag: 712e3fed-d82c-49a0-bbd3-60e10334675c

	column 'Province Code'
		dataType: int64
		isHidden
		lineageTag: ff6891fa-3e8d-4320-a4e2-a3c102e6e64b
		summarizeBy: none
		sourceColumn: Province Code

	column 'Province Name'
		dataType: string
		lineageTag: 58c180ef-39b8-4246-aa54-0ed64809dc6a
		summarizeBy: none
		sourceColumn: Province Name

	column Indicator
		dataType: string
		lineageTag: 4bca7464-ed16-4529-a071-2604228403c4
		summarizeBy: none
		sourceColumn: Indicator

	column 'Indicator Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2412e952-82cc-41ea-8418-66192cf1ceb9
		summarizeBy: none
		sourceColumn: Indicator Sort

	column 'Children Count'
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: 5cfeef4a-9593-40c1-9c6c-777dce0a7298
		summarizeBy: sum
		sourceColumn: Children Count

	column Percent
		dataType: double
		isHidden
		formatString: 0.0
		lineageTag: aa127c9b-890e-409d-bd19-cef98a739d14
		summarizeBy: sum
		sourceColumn: Percent

		annotation SummarizationSetBy = Automatic

	column 'Value Status'
		dataType: string
		lineageTag: 3bfa3750-1f2b-405d-9076-ee2571cc6640
		summarizeBy: none
		sourceColumn: Value Status

	partition 'Province Indicators' = m
		mode: import
		source =
				let
				    Source = CensusChildrenData,
				    #"Filtered Rows" = Table.SelectRows(Source, each [Record Type] = "Province Indicators"),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Rows", {"Province Code", "Province Name", "Indicator", "Indicator Sort", "Children Count", "Percent", "Value Status"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Selected Columns", {{"Province Code", Int64.Type}, {"Province Name", type text}, {"Indicator", type text}, {"Indicator Sort", Int64.Type}, {"Children Count", Int64.Type}, {"Percent", type number}, {"Value Status", type text}}, "en-CA")
				in
				    #"Changed Type"

