table 'CPI Annual'
	lineageTag: 08467b70-3518-4b8d-a5f1-ca9d1cf295f7

	measure 'CPI Annual Index' = ```
			
			AVERAGE ( 'CPI Annual'[VALUE] )
			
			```
		lineageTag: 042ad7e6-74e8-4ef6-a82e-a82b53132506

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI Annual YoY %' = ```
			
			VAR CurrYear = [CPI Annual Index]
			VAR PrevYear =
			    CALCULATE (
			        [CPI Annual Index],
			        DATEADD ( 'Annual Dates'[Date], -1, YEAR )
			    )
			RETURN
			DIVIDE ( CurrYear - PrevYear, PrevYear )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e3d66310-8547-43e7-b787-e09e558936d1

	measure 'CPI Annual YoY % Avg 5 Years' = ```

			VAR LatestDateWithYoY =
			    MAXX (
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date]
			    )
			VAR LastFiveAnnualDates =
			    TOPN (
			        5,
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            'Annual Dates'[Date] <= LatestDateWithYoY
			                && NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date],
			        DESC
			    )
			RETURN
			AVERAGEX ( LastFiveAnnualDates, [CPI Annual YoY %] )

			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9b7f0677-4f8a-42fd-87e9-a7221caf2f78

	measure 'CPI Annual YoY % Avg 10 Years' = ```

			VAR LatestDateWithYoY =
			    MAXX (
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date]
			    )
			VAR LastTenAnnualDates =
			    TOPN (
			        10,
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            'Annual Dates'[Date] <= LatestDateWithYoY
			                && NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date],
			        DESC
			    )
			RETURN
			AVERAGEX ( LastTenAnnualDates, [CPI Annual YoY %] )

			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8a46c71e-73b8-402f-82df-c2553b24be0e

	measure 'CPI Annual YoY % Avg 20 Years' = ```

			VAR LatestDateWithYoY =
			    MAXX (
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date]
			    )
			VAR LastTwentyAnnualDates =
			    TOPN (
			        20,
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            'Annual Dates'[Date] <= LatestDateWithYoY
			                && NOT ISBLANK ( [CPI Annual YoY %] )
			        ),
			        'Annual Dates'[Date],
			        DESC
			    )
			RETURN
			AVERAGEX ( LastTwentyAnnualDates, [CPI Annual YoY %] )

			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d0ff78d0-58c9-4c9a-9ce2-d3654a577f07

	measure 'CPI Annual YoY Abs' = ```
			
			VAR CurrYear = [CPI Annual Index]
			VAR PrevYear =
			    CALCULATE (
			        [CPI Annual Index],
			        DATEADD ( 'Annual Dates'[Date], -1, YEAR )
			    )
			RETURN
			CurrYear - PrevYear
			
			```
		formatString: 0
		lineageTag: b2c9adb8-c9f4-417e-8795-05c8ae9eea3b

	measure 'CPI Annual Index (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'Annual Dates'[Date] )
			RETURN
			CALCULATE (
			    [CPI Annual Index],
			    'Annual Dates'[Date] = LatestDate
			)
			
			```
		lineageTag: 2af42733-3672-4c38-b462-48a7c592f029

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI Annual YoY % (Latest)' = ```
			
			VAR LatestDateWithPY =
			    MAXX (
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            NOT ISBLANK (
			                CALCULATE (
			                    [CPI Annual Index],
			                    DATEADD ( 'Annual Dates'[Date], -1, YEAR )
			                )
			            )
			        ),
			        'Annual Dates'[Date]
			    )
			RETURN
			CALCULATE (
			    [CPI Annual YoY %],
			    'Annual Dates'[Date] = LatestDateWithPY
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f3b71f95-f210-4bfb-966f-a8691593c884

	measure 'CPI Annual YoY % Current' = [CPI Annual YoY % (Latest)]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e1ec0089-f89b-4a97-8c6c-95bb60f9480e

	measure 'CPI Annual YoY Abs (Latest)' = ```
			
			VAR LatestDateWithPY =
			    MAXX (
			        FILTER (
			            ALLSELECTED ( 'Annual Dates'[Date] ),
			            NOT ISBLANK (
			                CALCULATE (
			                    [CPI Annual Index],
			                    DATEADD ( 'Annual Dates'[Date], -1, YEAR )
			                )
			            )
			        ),
			        'Annual Dates'[Date]
			    )
			RETURN
			CALCULATE (
			    [CPI Annual YoY Abs],
			    'Annual Dates'[Date] = LatestDateWithPY
			)
			
			```
		formatString: 0.00
		lineageTag: 9bbc897e-fa5e-4a95-a1b9-edffb4f1dd95

	measure LatestDateTime = MAX('Annual Dates'[Date])
		formatString: General Date
		lineageTag: f040a99f-f81c-409b-bf90-1c2d3d13d657

	measure LatestDateTimeText = FORMAT([LatestDateTime], "yyyy-MM-dd")
		lineageTag: f5c97ef7-e46e-4777-b5fc-29a2af52e0f1

	column GEO
		dataType: string
		lineageTag: 8c434b04-f73c-4e25-91f6-f01a132029a7
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Products and product groups'
		dataType: string
		lineageTag: bd33027d-d5f9-4cf5-85c9-586ae8b3f416
		summarizeBy: none
		sourceColumn: Products and product groups

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 595f2b94-a348-4d7c-9161-fa7f9de96c77
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column SCALAR_FACTOR
		dataType: string
		lineageTag: fc2e27a6-1027-4fe0-a9d9-9882c94c1fa2
		summarizeBy: none
		sourceColumn: SCALAR_FACTOR

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: cef25db3-6d6a-4556-94bd-4322da3c190d
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REF_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dcf8405-9440-422c-9fb6-9c48ce62ff08
		summarizeBy: none
		sourceColumn: REF_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'CPI Annual' = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/18100005-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", Int64.Type}, {"GEO", type text}, {"DGUID", type text}, {"Products and product groups", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type number}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Remove Columns" = Table.RemoveColumns(#"Changed Type",{"DECIMALS", "TERMINATED", "SYMBOL", "STATUS", "COORDINATE", "VECTOR", "DGUID", "UOM_ID", "SCALAR_ID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Remove Columns", each [REF_DATE] > 2001),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "REF_DATE_Date", each #date(Number.From([REF_DATE]), 1, 1)),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"REF_DATE"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"REF_DATE_Date", "REF_DATE"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"REF_DATE", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

