table JVWS
	lineageTag: 0a3435d5-4426-442d-9ada-789dbe49fbe1

	measure 'Job Vacancies' = ```
			
			CALCULATE(
			    SUM('JVWS'[VALUE]),
			    'JVWS'[Statistics] = "Job vacancies"
			)
			
			```
		lineageTag: 8882ed90-b211-4186-858d-604a769febac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Offered Hourly Wage' = ```
			
			CALCULATE(
			    AVERAGE('JVWS'[VALUE]),
			    'JVWS'[Statistics] = "Average offered hourly wage"
			)
			
			```
		lineageTag: 3c1a530f-f514-499a-bba4-4ba7e8b26598

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (MoM Abs - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevDate   = EDATE(_LatestDate, -1)
			VAR _LatestVal =
			    CALCULATE([Job Vacancies], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Job Vacancies], TREATAS({_PrevDate}, DateTable[Date]))
			RETURN
			_LatestVal - _PrevVal
			
			```
		lineageTag: af2f6806-5ded-44c7-881f-2f632c76f7b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (MoM %)' = ```
			
			VAR Prev =
			    CALCULATE(
			        [Job Vacancies],
			        DATEADD(DateTable[Date], -1, MONTH)
			    )
			RETURN
			DIVIDE([Job Vacancies] - Prev, Prev)
			
			```
		lineageTag: a64aa2f6-2860-42e1-aab7-d7fe1b21277b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (YoY Abs)' =
			VAR _Current = [Job Vacancies]
			VAR _PrevYear =
			    CALCULATE(
			        [Job Vacancies],
			        DATEADD(DateTable[Date], -12, MONTH)
			    )
			RETURN
			    IF(
			        ISBLANK(_Current) || ISBLANK(_PrevYear),
			        BLANK(),
			        _Current - _PrevYear
			    )
		lineageTag: 578f1bbd-76fb-4ae6-a60d-3058a2d30c27

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (YoY %)' =
			VAR _Current = [Job Vacancies]
			VAR _PrevYear =
			    CALCULATE(
			        [Job Vacancies],
			        DATEADD(DateTable[Date], -12, MONTH)
			    )
			RETURN
			    IF(
			        ISBLANK(_Current) || ISBLANK(_PrevYear),
			        BLANK(),
			        DIVIDE(_Current - _PrevYear, _PrevYear)
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 825f2c72-51a6-4ee3-9fc8-3a4fe8930f8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (MoM Abs)' = ```
			
			VAR Prev =
			    CALCULATE(
			        [Avg Offered Hourly Wage],
			        DATEADD(DateTable[Date], -1, MONTH)
			    )
			RETURN
			[Avg Offered Hourly Wage] - Prev
			
			```
		lineageTag: 0260a4d2-cb49-4a72-9cf2-2710ccc2b166

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (MoM %)' = ```
			
			VAR Prev =
			    CALCULATE(
			        [Avg Offered Hourly Wage],
			        DATEADD(DateTable[Date], -1, MONTH)
			    )
			RETURN
			DIVIDE([Avg Offered Hourly Wage] - Prev, Prev)
			
			```
		lineageTag: 81d830b1-01c8-4aae-8814-717af602552e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (YoY Abs)' =
			VAR _Current = [Avg Offered Hourly Wage]
			VAR _PrevYear =
			    CALCULATE(
			        [Avg Offered Hourly Wage],
			        DATEADD(DateTable[Date], -12, MONTH)
			    )
			RETURN
			    IF(
			        ISBLANK(_Current) || ISBLANK(_PrevYear),
			        BLANK(),
			        _Current - _PrevYear
			    )
		lineageTag: bb6ff7e6-c6d5-4411-802e-cba08a4f5fe0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (YoY %)' =
			VAR _Current = [Avg Offered Hourly Wage]
			VAR _PrevYear =
			    CALCULATE(
			        [Avg Offered Hourly Wage],
			        DATEADD(DateTable[Date], -12, MONTH)
			    )
			RETURN
			    IF(
			        ISBLANK(_Current) || ISBLANK(_PrevYear),
			        BLANK(),
			        DIVIDE(_Current - _PrevYear, _PrevYear)
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ddded294-c97a-4053-9a0d-7d9638390df6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Latest Month' = ```
			
			CALCULATE(
			    MAX('JVWS'[Date]),
			    REMOVEFILTERS(DateTable)
			)
			
			```
		formatString: General Date
		lineageTag: 5609abf5-34ef-4826-a3be-fe5d7b33df44

	measure 'Job Vacancies (Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			RETURN
			CALCULATE(
			    [Job Vacancies],
			    TREATAS({_LatestDate}, DateTable[Date])
			)
			
			```
		lineageTag: 9f1243e2-e579-4ab6-b8ad-4a239eeaecb0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			RETURN
			CALCULATE(
			    [Avg Offered Hourly Wage],
			    TREATAS({_LatestDate}, DateTable[Date])
			)
			
			```
		lineageTag: 6818677d-c169-4a7c-a4d1-7cee3e88b5be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (MoM % - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevDate   = EDATE(_LatestDate, -1)
			VAR _LatestVal =
			    CALCULATE([Job Vacancies], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Job Vacancies], TREATAS({_PrevDate}, DateTable[Date]))
			RETURN
			DIVIDE(_LatestVal - _PrevVal, _PrevVal)
			
			```
		lineageTag: d154384c-9bbf-4655-ba70-6eecbfa637d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (MoM Abs - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevDate   = EDATE(_LatestDate, -1)
			VAR _LatestVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_PrevDate}, DateTable[Date]))
			RETURN
			_LatestVal - _PrevVal
			
			```
		lineageTag: 96afaa41-5bb2-4c86-9934-d1dc1bb882ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (MoM % - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevDate   = EDATE(_LatestDate, -1)
			VAR _LatestVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_PrevDate}, DateTable[Date]))
			RETURN
			DIVIDE(_LatestVal - _PrevVal, _PrevVal)
			
			```
		lineageTag: 49aa52b0-cbed-43c5-a480-25a6de2bb0c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (YoY Abs - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevYear   = EDATE(_LatestDate, -12)
			VAR _LatestVal =
			    CALCULATE([Job Vacancies], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Job Vacancies], TREATAS({_PrevYear}, DateTable[Date]))
			RETURN
			_LatestVal - _PrevVal
			
			```
		lineageTag: 0e94959f-e40d-442e-af03-6b8ea8938a78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (YoY % - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevYear   = EDATE(_LatestDate, -12)
			VAR _LatestVal =
			    CALCULATE([Job Vacancies], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Job Vacancies], TREATAS({_PrevYear}, DateTable[Date]))
			RETURN
			DIVIDE(_LatestVal - _PrevVal, _PrevVal)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 49b01f08-5150-4f33-9991-fdbeeaeddebd

	measure 'Avg Wage (YoY Abs - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevYear   = EDATE(_LatestDate, -12)
			VAR _LatestVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_PrevYear}, DateTable[Date]))
			RETURN
			_LatestVal - _PrevVal
			
			```
		lineageTag: 436b6b7e-1755-40a7-af33-7e739ed08026

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Wage (YoY % - Latest)' = ```
			
			VAR _LatestDate = [Latest Month]
			VAR _PrevYear   = EDATE(_LatestDate, -12)
			VAR _LatestVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_LatestDate}, DateTable[Date]))
			VAR _PrevVal =
			    CALCULATE([Avg Offered Hourly Wage], TREATAS({_PrevYear}, DateTable[Date]))
			RETURN
			DIVIDE(_LatestVal - _PrevVal, _PrevVal)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 39a342cd-678d-493f-99f4-d49a2ed1c177

	measure 'Job Vacancies (Quarter Avg)' = ```
			
			AVERAGEX(
			    VALUES(DateTable[Date]),
			    [Job Vacancies]
			)
			
			```
		lineageTag: 0f1ffac3-08a0-483c-ad1b-ca4bdfee400a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies (Base 2019 Q1)' = ```
			
			CALCULATE(
			    [Job Vacancies (Quarter Avg)],
			    REMOVEFILTERS(DateTable),
			    DateTable[Year] = 2019,
			    DateTable[QuarterNumber] = 1
			)
			
			```
		lineageTag: 90eb6c42-2ed6-4cdc-90f8-7ecebd119402

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Vacancies Index (2019 Q1)' = ```
			
			VAR BaseVal = [Job Vacancies (Base 2019 Q1)]
			VAR CurrVal = [Job Vacancies (Quarter Avg)]
			RETURN
			IF(
			    ISBLANK(BaseVal),
			    BLANK(),
			    100 * DIVIDE(CurrVal, BaseVal)
			)
			
			```
		lineageTag: 44828418-9aed-4c0e-b8c7-1fa143427801

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Returns the YoY percent-change measure selected by the JVWS Statistics slicer. Supports job vacancies and average offered hourly wage.
	measure 'Selected YoY Change %' =
			VAR _Statistic = SELECTEDVALUE('JVWS'[Statistics], "Job vacancies")
			RETURN
			    SWITCH(
			        _Statistic,
			        "Average offered hourly wage", [Avg Wage (YoY %)],
			        "Job vacancies", [Job Vacancies (YoY %)],
			        BLANK()
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: YoY Analysis
		lineageTag: f1e45152-a55d-4d51-bf0c-48e3a9406c86

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 740669a4-14c6-4667-8946-57bff91fe643
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GEO
		dataType: string
		lineageTag: 593524e4-d88e-4854-91ac-d1b9b0190132
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'National Occupational Classification'
		dataType: string
		lineageTag: 358f31d2-ea05-49b7-b0ee-004049defa5c
		summarizeBy: none
		sourceColumn: National Occupational Classification

		annotation SummarizationSetBy = Automatic

	column Statistics
		dataType: string
		lineageTag: a3b18cac-44be-46e3-aac4-b98e5ec724e1
		summarizeBy: none
		sourceColumn: Statistics

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: 2a6c5dfa-5846-482a-aaec-a2fdedaa695d
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOC_5
		dataType: string
		lineageTag: 85897780-a201-44ac-89f9-c7d8f93d7361
		summarizeBy: none
		sourceColumn: NOC_5

		annotation SummarizationSetBy = Automatic

	column 'Occupation Label'
		dataType: string
		lineageTag: 096418d0-28d2-4a1a-a9d8-3e9ed9de3925
		summarizeBy: none
		sourceColumn: Occupation Label

		annotation SummarizationSetBy = Automatic

	column NOC_Length
		dataType: string
		lineageTag: fcc8131c-ba31-4993-8ce9-c13f49f90982
		summarizeBy: none
		sourceColumn: NOC_Length

		annotation SummarizationSetBy = Automatic

	partition JVWS = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100444-eng.zip"),
				    Custom1 = Unzip (Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", type date}, {"GEO", type text}, {"DGUID", type text}, {"National Occupational Classification", type text}, {"Statistics", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"UOM", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS", "DGUID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"REF_DATE", "Date"}}),
				    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Renamed Columns", "Text Between Delimiters", each Text.BetweenDelimiters([National Occupational Classification], "[", "]"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Between Delimiters",{{"Text Between Delimiters", "NOC_5"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Occupation Label", each Text.BeforeDelimiter([National Occupational Classification], " [") & " (" & [NOC_5] & ")"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "NOC_Length", each Text.Length([NOC_5]))
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

