table 'CPI Weights'
	lineageTag: 3a4f2e6c-9e2b-4c96-9f5e-45e2d055e116

	measure 'CPI Weight %' =
			DIVIDE ( AVERAGE ( 'CPI Weights'[VALUE] ), 100 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 76e1fb0b-1b88-4d72-a790-e5e03ea1e492

	measure 'CPI Weight % (Latest)' =
			VAR LatestWeightYear =
				CALCULATE (
					MAX ( 'CPI Weights'[REF_DATE] ),
					REMOVEFILTERS ( 'CPI Weights'[REF_DATE] )
				)
			RETURN
				CALCULATE (
					[CPI Weight %],
					'CPI Weights'[REF_DATE] = LatestWeightYear
				)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 13384b56-8cb8-48e6-9d7b-9a345337c5bb

	measure 'Child Care CPI Weight % (Latest)' =
			CALCULATE (
				[CPI Weight % (Latest)],
				KEEPFILTERS ( 'CPI Weights'[Products and product groups] = "Child care services" )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bc11cf06-65a5-49bd-8cf0-9af550a63d8a

	measure 'Child Care CPI Weight Change (pp)' =
			VAR LatestWeightYear =
				CALCULATE (
					MAX ( 'CPI Weights'[REF_DATE] ),
					REMOVEFILTERS ( 'CPI Weights'[REF_DATE] )
				)
			VAR PreviousWeightYear =
				CALCULATE (
					MAX ( 'CPI Weights'[REF_DATE] ),
					REMOVEFILTERS ( 'CPI Weights'[REF_DATE] ),
					'CPI Weights'[REF_DATE] < LatestWeightYear
				)
			VAR LatestWeight =
				CALCULATE (
					[CPI Weight %],
					KEEPFILTERS ( 'CPI Weights'[Products and product groups] = "Child care services" ),
					'CPI Weights'[REF_DATE] = LatestWeightYear
				)
			VAR PreviousWeight =
				CALCULATE (
					[CPI Weight %],
					KEEPFILTERS ( 'CPI Weights'[Products and product groups] = "Child care services" ),
					'CPI Weights'[REF_DATE] = PreviousWeightYear
				)
			RETURN
				( LatestWeight - PreviousWeight ) * 100
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		lineageTag: f9e0ca21-31c8-48f0-899c-2a785e914381

	measure 'Child Care CPI Index' =
			VAR SelectedGeographies = VALUES ( 'CPI Weights'[GEO] )
			RETURN
				CALCULATE (
					[CPI Index],
					KEEPFILTERS ( 'CPI'[Products and product groups] = "Child care services" ),
					TREATAS ( SelectedGeographies, 'CPI'[GEO] )
				)
		formatString: 0.00
		lineageTag: 6f5bdaf0-a9fc-4f57-8aea-f1a34be143f3

	measure 'Child Care CPI Index (Latest)' =
			VAR SelectedGeographies = VALUES ( 'CPI Weights'[GEO] )
			RETURN
				CALCULATE (
					[CPI Index (Latest)],
					KEEPFILTERS ( 'CPI'[Products and product groups] = "Child care services" ),
					TREATAS ( SelectedGeographies, 'CPI'[GEO] )
				)
		formatString: 0.00
		lineageTag: 1a663da8-396f-4fd9-bd96-26e2317f8d33

	measure 'Child Care CPI YoY % (Latest)' =
			VAR SelectedGeographies = VALUES ( 'CPI Weights'[GEO] )
			RETURN
				CALCULATE (
					[CPI YoY % (Latest)],
					KEEPFILTERS ( 'CPI'[Products and product groups] = "Child care services" ),
					TREATAS ( SelectedGeographies, 'CPI'[GEO] )
				)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 0b492b62-925d-4b10-9706-f5ab8bb73c10

	measure 'Child Care CPI Contribution (pp)' =
			[Child Care CPI Weight % (Latest)]
				* [Child Care CPI YoY % (Latest)]
				* 100
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		lineageTag: 085d82e8-8c12-4774-a2d9-1e7537a1d70d

	column REF_DATE
		dataType: int64
		formatString: 0
		lineageTag: 99cdd019-2165-4e9f-99c9-1d728f21e0eb
		summarizeBy: none
		sourceColumn: REF_DATE

		annotation SummarizationSetBy = Automatic

	column GEO
		dataType: string
		lineageTag: 5e08a7d1-1542-4a6f-954e-e785eb2df2b5
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Products and product groups'
		dataType: string
		lineageTag: 9fd526e9-a57f-4ef2-9b66-3dc058a6565f
		summarizeBy: none
		sourceColumn: Products and product groups

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: c3f3e087-2952-41d2-98a8-770b7b63ad69
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

	column 'Price period of weight'
		dataType: string
		lineageTag: 437dff5e-7139-4126-bc28-3b790d7c95b6
		summarizeBy: none
		sourceColumn: Price period of weight

		annotation SummarizationSetBy = Automatic

	column 'Geographic distribution of weight'
		dataType: string
		lineageTag: 11e8de9e-73fe-4d43-97fc-8ce8db0fd9d2
		summarizeBy: none
		sourceColumn: Geographic distribution of weight

		annotation SummarizationSetBy = Automatic

	partition 'CPI Weights' = m
		mode: import
		source =
				let
					Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/18100007-eng.zip"),
					Custom1 = Unzip(Source),
					Content = Custom1{0}[Content],
					#"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", Int64.Type}, {"GEO", type text}, {"DGUID", type text}, {"Products and product groups", type text}, {"Price period of weight", type text}, {"Geographic distribution of weight", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
					#"Filtered Rows" = Table.SelectRows(#"Changed Type", each [REF_DATE] >= 2002 and [#"Price period of weight"] = "Weight at basket link month prices" and [#"Geographic distribution of weight"] = "Distribution to selected geographies"),
					#"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"DGUID", "UOM", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"})
				in
					#"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
