table CPI
	lineageTag: c02d0ce5-fd2f-4ab5-a127-1b394ca9056e

	measure 'CPI 12M MA' = ```
			
			AVERAGEX (
			    DATESINPERIOD ( 'CPI'[REF_DATE], MAX ( 'CPI Weights'[REF_DATE] ), -12, MONTH ),
			    [CPI Index]
			)
			
			```
		lineageTag: c9cc4dfa-d93a-4500-b742-7e44591e8755

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI Index' = ```
			
			AVERAGE ( 'CPI'[VALUE] )
			
			```
		lineageTag: dce13896-d62e-4e3b-9568-77071913c997

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI Index (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'CPI'[REF_DATE] )
			RETURN
			CALCULATE (
			    [CPI Index],
			    'CPI'[REF_DATE] = LatestDate
			)
			
			```
		formatString: 0.00
		lineageTag: dd1076c0-ec30-4493-b1c8-d4066f4c98c2

	measure 'CPI MoM %' = ```
			
			VAR CurrMonth = [CPI Index]
			VAR PrevMonth =
			    CALCULATE (
			        [CPI Index],
			        DATEADD ( 'CPI'[REF_DATE], -1, MONTH )    )
			RETURN
			DIVIDE ( CurrMonth - PrevMonth, PrevMonth )
			
			```
		lineageTag: 7a1e3d2d-5328-48e4-9f98-e45d644cdfbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI MoM % (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'CPI'[REF_DATE] )
			RETURN
			CALCULATE (
			    [CPI MoM %],
			    'CPI'[REF_DATE] = LatestDate
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 330d1af2-1d54-4e8d-b92a-6998d0794993

	measure 'CPI MoM Abs' = ```
			
			VAR CurrMonth = [CPI Index]
			VAR PrevMonth =
			    CALCULATE (
			        [CPI Index],
			        DATEADD ( 'CPI'[REF_DATE], -1, MONTH )
			    )
			RETURN
			CurrMonth - PrevMonth
			
			```
		formatString: 0.00
		lineageTag: f26e71f1-ac3c-4a4d-890e-16ab68dee6a2

	measure 'CPI MoM Abs (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'CPI'[REF_DATE] )
			RETURN
			CALCULATE (
			    [CPI MoM Abs],
			    'CPI'[REF_DATE] = LatestDate
			)
			
			```
		formatString: 0.00
		lineageTag: 71053e8f-718c-4c8b-bbba-64ac6cdad296

	measure 'CPI YoY %' =
			
			VAR CurrKey =
			    MAX ( 'CPI'[YearMonthKey] )
			
			VAR CurrYear =
			    QUOTIENT ( CurrKey, 100 )
			
			VAR CurrMonth =
			    MOD ( CurrKey, 100 )
			
			VAR PrevKey =
			    ( CurrYear - 1 ) * 100 + CurrMonth
			
			VAR CurrVal =
			    [CPI Index]
			
			VAR PrevVal =
			    CALCULATE (
			        [CPI Index],
			        REMOVEFILTERS ( 'CPI'[MonthStart] ),
			        REMOVEFILTERS ( 'CPI'[REF_DATE] ),
			        REMOVEFILTERS ( 'CPI'[YearMonthKey] ),
			        'CPI'[YearMonthKey] = PrevKey
			    )
			
			RETURN
			DIVIDE ( CurrVal - PrevVal, PrevVal )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 58d885d6-8ca4-4a41-b441-1fa8a83aabc3

	measure 'CPI YoY % (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'CPI'[REF_DATE] )
			RETURN
			CALCULATE (
			    [CPI YoY %],
			    'CPI'[REF_DATE] = LatestDate
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e4585f1a-0d21-485e-8f9b-785d26cecf98

	measure 'CPI YoY Abs' = ```
			
			VAR CurrMonth = [CPI Index]
			VAR PrevYear =
			    CALCULATE (
			        [CPI Index],
			        DATEADD ( 'CPI'[REF_DATE], -1, YEAR )
			    )
			RETURN
			CurrMonth - PrevYear
			
			```
		formatString: 0.00
		lineageTag: c872ef4b-bcda-4556-a7bd-b874511e6884

	measure 'CPI YoY Abs (Latest)' = ```
			
			VAR LatestDate =
			    MAX ( 'CPI'[REF_DATE] )
			RETURN
			CALCULATE (
			    [CPI YoY Abs],
			    'CPI'[REF_DATE] = LatestDate
			)
			
			```
		formatString: 0.00
		lineageTag: 4761d5c4-2243-4442-bfd4-4cc7d1dccc44

	measure 'CPI Previous Year Index - Debug' =
			
			VAR CurrKey =
			    MAX ( 'CPI'[YearMonthKey] )
			
			VAR CurrYear =
			    QUOTIENT ( CurrKey, 100 )
			
			VAR CurrMonth =
			    MOD ( CurrKey, 100 )
			
			VAR PrevKey =
			    ( CurrYear - 1 ) * 100 + CurrMonth
			
			RETURN
			CALCULATE (
			    [CPI Index],
			    FILTER (
			        ALL ( 'CPI'[YearMonthKey], 'CPI'[MonthStart], 'CPI'[REF_DATE] ),
			        'CPI'[YearMonthKey] = PrevKey
			    )
			)
		lineageTag: 8b1422e0-817f-404e-b70c-b61ea9aff144

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPI PrevKey - Debug' =
			
			VAR CurrKey =
			    MAX ( 'CPI'[YearMonthKey] )
			
			VAR CurrYear =
			    QUOTIENT ( CurrKey, 100 )
			
			VAR CurrMonth =
			    MOD ( CurrKey, 100 )
			
			RETURN
			( CurrYear - 1 ) * 100 + CurrMonth
		formatString: 0
		lineageTag: 14804af0-eb8d-4f64-866d-d65e425415d5

	column REF_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9cff7492-950f-459f-a368-902dc8e2a063
		summarizeBy: none
		sourceColumn: REF_DATE

		variation Variation
			isDefault
			relationship: 3fe3abb5-80cf-4add-a586-92501e641114
			defaultHierarchy: LocalDateTable_7929a108-81d3-4c08-ac72-a7bb42b0221a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GEO
		dataType: string
		lineageTag: 0c907266-21a9-4bfc-9985-77ba52ce83ca
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Products and product groups'
		dataType: string
		lineageTag: f30bd0e3-b8f5-4500-90aa-9e846c73e950
		summarizeBy: none
		sourceColumn: Products and product groups

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 4f5e3524-8169-4c18-994c-798b73dcd2ab
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column SCALAR_FACTOR
		dataType: string
		lineageTag: 93331ace-221e-42c6-bc8c-1b26eb5b1349
		summarizeBy: none
		sourceColumn: SCALAR_FACTOR

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: a2f37084-ed9f-455d-a490-96c9aed89312
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthStart =
			
			DATE (
			    YEAR ( 'CPI'[REF_DATE] ),
			    MONTH ( 'CPI'[REF_DATE] ),
			    1
			)
		formatString: Long Date
		lineageTag: 2eb2daa9-9869-4d49-b1a4-95adb5662a14
		summarizeBy: none

		variation Variation
			isDefault
			relationship: dba5129d-3109-492c-9d22-d44148e44485
			defaultHierarchy: LocalDateTable_5960ad3e-b7ae-47e0-8ad2-c5e29e76ac9d.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YearMonthKey =
			
			YEAR ( 'CPI'[MonthStart] ) * 100
			    + MONTH ( 'CPI'[MonthStart] )
		formatString: 0
		lineageTag: af852b78-9480-4398-bcfa-06e6c3425bf7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition CPI = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/18100004-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", type date}, {"GEO", type text}, {"DGUID", type text}, {"Products and product groups", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type number}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Remove Columns" = Table.RemoveColumns(#"Changed Type",{"DECIMALS", "TERMINATED", "SYMBOL", "STATUS", "COORDINATE", "VECTOR", "DGUID", "UOM_ID", "SCALAR_ID"}),
				    #"Filter Rows" = Table.SelectRows(#"Remove Columns", each [REF_DATE] > #date(2001, 12, 31))
				in
				    #"Filter Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

