table LFS_FamilyStructure_14100396_Annual
	lineageTag: cdc2a7af-82ea-4ebb-8ac4-8bfd8f375351

	measure 'Base Value (Annual)' = ```
			
			SUM ( 'LFS_FamilyStructure_14100396_Annual'[VALUE] )
			
			```
		lineageTag: 12d496a8-a065-4254-b576-bc3d97a635b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Latest Year' = ```
			
			CALCULATE(
			    MAX(YearTable[Year]),
			    REMOVEFILTERS(YearTable)
			)
			
			```
		formatString: 0
		lineageTag: cfd14884-7512-4aef-8b7d-22b9c49511cb

	measure 'Annual Metric - Participation Rate (Mothers)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			
			```
		lineageTag: 84a1f116-ecb0-41ed-a3d5-d264a8bddf6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Metric - Unemployment Rate (Mothers)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			
			```
		lineageTag: 4a146741-44df-4385-8767-097d97479bf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Motherhood Gap (pp)' = ```
			
			[Annual PR - NoKids<18 (Canada)] - [Annual PR - Mothers (Canada)]
			
			```
		lineageTag: 1b9bd7cd-16a1-4b5b-af17-2a76b0beb848

	measure 'Annual Metric - Latest' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    SELECTEDMEASURE(),
			    YearTable[Year] = y
			)
			
			```
		lineageTag: 86bf6e4f-cc39-4bc4-af31-6cfaad4456ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Metric YoY (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(SELECTEDMEASURE(), YearTable[Year] = y)
			-
			CALCULATE(SELECTEDMEASURE(), YearTable[Year] = y - 1)
			
			```
		lineageTag: 1d83c794-f934-45d1-b962-f082592a89ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Metric vs 2019 (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(SELECTEDMEASURE(), YearTable[Year] = y)
			-
			CALCULATE(SELECTEDMEASURE(), YearTable[Year] = 2019)
			
			```
		lineageTag: bf635557-b5a8-43b7-a511-c1bbbe53bcc5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR - NoKids<18 (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Without children less than 18 years"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate")
			)
			
			```
		lineageTag: fecfca1d-d06b-490f-a8b8-7ad18f530103

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR - Mothers (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			
			```
		lineageTag: 0c4465b4-f55c-4ea2-9efc-b0c5f8874a9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR - Mothers (Quebec)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Quebec",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			
			```
		lineageTag: dec45a07-c31e-4f34-afc1-378a0eff30cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR Mothers (Latest)' = ```
			
			VAR y = [Latest Year]
			RETURN CALCULATE([Annual PR - Mothers (Canada)], YearTable[Year] = y)
			
			```
		lineageTag: 8e607294-bf3d-4bbb-a3bf-6f9c4ec1513b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR Mothers YoY (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE([Annual PR - Mothers (Canada)], YearTable[Year] = y)
			-
			CALCULATE([Annual PR - Mothers (Canada)], YearTable[Year] = y - 1)
			
			```
		lineageTag: 08676eef-1d42-40d4-8c60-8acacde61b09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR Mothers vs 2019 (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE([Annual PR - Mothers (Canada)], YearTable[Year] = y)
			-
			CALCULATE([Annual PR - Mothers (Canada)], YearTable[Year] = 2019)
			
			```
		lineageTag: 81699bd9-606b-432e-b76e-bef88d548c01

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual UR - Mothers (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			
			```
		lineageTag: 55dcfcfd-2e1f-46b5-b249-c7ef8ecd7f9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual UR Mothers (Latest)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			
			```
		lineageTag: 1d28bcc2-77c6-4cb5-8923-0970c8c830dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Pop - Mothers (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Population"
			)
			
			```
		lineageTag: 28e79da1-1868-4382-a533-82173d41246c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual LF - Mothers (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Labour force"
			)
			
			```
		lineageTag: cef07fe4-183c-4de9-9317-674a04abf01e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Emp - Mothers (Canada)' = ```
			
			CALCULATE(
			    [Base Value (Annual)],
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Employment"
			)
			
			```
		lineageTag: 62eb2b1c-d079-415b-9446-bf197c8c9be2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Gap vs Quebec (pp)' = ```
			
			[Annual PR - Mothers (Quebec)] - [Annual PR - Mothers (Canada)]
			
			```
		lineageTag: 05bea42c-420f-426b-82fb-64536f4f7770

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Motherhood Gap vs 2019 (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE([Annual Motherhood Gap (pp)], YearTable[Year] = y)
			-
			CALCULATE([Annual Motherhood Gap (pp)], YearTable[Year] = 2019)
			
			```
		lineageTag: d42703db-b5a6-49ca-b61e-b57813b69403

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Gap vs Quebec vs 2019 (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE([Annual Gap vs Quebec (pp)], YearTable[Year] = y)
			-
			CALCULATE([Annual Gap vs Quebec (pp)], YearTable[Year] = 2019)
			
			```
		lineageTag: 100d17b1-7eb5-4865-973c-0197178476ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Motherhood Gap YoY (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE([Annual Motherhood Gap (pp)], YearTable[Year] = y)
			-
			CALCULATE([Annual Motherhood Gap (pp)], YearTable[Year] = y - 1)
			
			```
		lineageTag: abe699e8-00a6-4f28-b315-62e93e3eb24e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Motherhood Gap (Latest, pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Annual Motherhood Gap (pp)],
			    YearTable[Year] = y
			)
			
			```
		lineageTag: 55d1ddf7-fad7-4bf5-a357-224f3992968c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR Mothers (Latest Year, by GEO)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years"),
			    KEEPFILTERS('LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"),
			    ALLEXCEPT('LFS_FamilyStructure_14100396_Annual', 'LFS_FamilyStructure_14100396_Annual'[GEO])
			)
			
			```
		lineageTag: 774326e4-2c26-4a3f-a9a5-9d2b6b614b44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rate Value (Annual)' = ```
			
			MAX ( 'LFS_FamilyStructure_14100396_Annual'[VALUE] )
			
			```
		lineageTag: a1367f13-9ceb-4fe5-b1c1-0d85e4b8ea8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual PR Mothers (Latest Year, by Province)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			
			```
		formatString: 0.0
		lineageTag: 6c359fe4-b220-41b3-9d75-7224d8d50d0e

	measure 'Annual PR Mothers (pp change vs 2019) by Province' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			-
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = 2019,
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Participation rate"
			)
			
			```
		lineageTag: 9b2690b8-8f14-4e23-8343-5f8aee461a25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual UR Mothers YoY (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			-
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y - 1,
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			
			```
		lineageTag: d063413e-6383-451a-9717-52d1d4e3b215

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual UR Mothers vs 2019 (pp)' = ```
			
			VAR y = [Latest Year]
			RETURN
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = y,
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			-
			CALCULATE(
			    [Rate Value (Annual)],
			    YearTable[Year] = 2019,
			    'LFS_FamilyStructure_14100396_Annual'[GEO] = "Canada",
			    'LFS_FamilyStructure_14100396_Annual'[Age] = "25 to 54 years",
			    'LFS_FamilyStructure_14100396_Annual'[Gender] = "Women+",
			    'LFS_FamilyStructure_14100396_Annual'[Family age composition] = "Youngest child 0 to 5 years",
			    'LFS_FamilyStructure_14100396_Annual'[Labour force characteristics] = "Unemployment rate"
			)
			
			```
		lineageTag: d6ae3bd9-eca7-4d56-a2d7-001e94cb265e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected LFS Value (Annual)' =
			
			MAX ( 'LFS_FamilyStructure_14100396_Annual'[VALUE] )
		lineageTag: f7aa0326-5bba-473b-bd8c-227892b483ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected LFS Value YoY Change (Annual)' =
			
			VAR CurrentYear =
			    MAX ( YearTable[Year] )
			VAR CurrentValue =
			    [Selected LFS Value (Annual)]
			VAR PreviousYearValue =
			    CALCULATE(
			        [Selected LFS Value (Annual)],
			        YearTable[Year] = CurrentYear - 1
			    )
			RETURN
			IF(
			    ISBLANK(CurrentValue) || ISBLANK(PreviousYearValue),
			    BLANK(),
			    CurrentValue - PreviousYearValue
			)
		lineageTag: 8cfc8b9a-9ad8-481d-a73c-55a5d220105c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REF_DATE
		dataType: int64
		formatString: 0
		lineageTag: cd90768d-68da-44c1-810a-4ba7d3f5721d
		summarizeBy: none
		sourceColumn: REF_DATE

		annotation SummarizationSetBy = Automatic

	column GEO
		dataType: string
		lineageTag: 676d10d4-3c64-46b6-bcf1-9793bda5d07f
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Labour force characteristics'
		dataType: string
		lineageTag: 0a903ca8-3776-4a96-912a-0b95ee244a81
		summarizeBy: none
		sourceColumn: Labour force characteristics

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: 4a91f2b8-9e95-4711-9f4b-12a35df3f7d6
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: ac1f231b-fc90-46f4-85a0-dc3fd37e56cb
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Family type'
		dataType: string
		lineageTag: 06cc3d05-c767-4fcc-aea8-e0f8ca09fbb9
		summarizeBy: none
		sourceColumn: Family type

		annotation SummarizationSetBy = Automatic

	column 'Family age composition'
		dataType: string
		lineageTag: 4cb797e2-5d0f-4af8-992c-1c8da1d5638f
		summarizeBy: none
		sourceColumn: Family age composition

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: f414ab62-233a-4e58-93c3-98643645b4ac
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition LFS_FamilyStructure_14100396_Annual = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100396-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", Int64.Type}, {"GEO", type text}, {"DGUID", type text}, {"Labour force characteristics", type text}, {"Age", type text}, {"Gender", type text}, {"Family type", type text}, {"Family age composition", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"DGUID", "UOM", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

