table 'SEPH Employment'
	lineageTag: 1cab2b56-ea91-4724-bd89-1b40cf2eeafc

	measure 'Employment Value' =
			
			MAX ( 'SEPH Employment'[VALUE] )
		formatString: 0
		lineageTag: 7e4e867b-f089-4e98-b8c3-ec26eeb4d362

	measure 'Child Care Payroll Employment' =
			
			CALCULATE (
			    [Employment Value],
			    'SEPH Employment'[NAICS] = "Child day-care services [6244]",
			    'SEPH Employment'[Employee Type] = "All employees"
			)
		formatString: 0
		lineageTag: 2352bde0-b2cd-4455-a002-d685a99fe250

	measure 'All Industries Payroll Employment' =
			
			CALCULATE (
			    [Employment Value],
			    'SEPH Employment'[NAICS] = "Industrial aggregate excluding unclassified businesses [11-91N]",
			    'SEPH Employment'[Employee Type] = "All employees"
			)
		formatString: 0
		lineageTag: 08679261-dc22-4dde-b98c-6e409251c79c

	measure 'Child Care Share of Payroll Employment' =
			
			DIVIDE (
			    [Child Care Payroll Employment],
			    [All Industries Payroll Employment]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08f45ff0-88ff-4745-92f9-36be9a2088df

	measure 'Child Care Payroll Employment YoY %' =
			
			VAR CurrentValue = [Child Care Payroll Employment]
			VAR PreviousValue =
			    CALCULATE (
			        [Child Care Payroll Employment],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			RETURN
			    DIVIDE ( CurrentValue - PreviousValue, PreviousValue )
		lineageTag: 95b4cf16-e71e-4c5e-bbc0-7d315b23b7d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Payroll Employment YoY %' =
			
			VAR CurrentValue = [All Industries Payroll Employment]
			VAR PreviousValue =
			    CALCULATE (
			        [All Industries Payroll Employment],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			RETURN
			    DIVIDE ( CurrentValue - PreviousValue, PreviousValue )
		lineageTag: 43cf1f44-02a3-430b-8438-8c6278906e3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Payroll Employment Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Payroll Employment],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		formatString: 0
		lineageTag: ac88f746-7154-4e90-b29a-4cecf1e062bd

	measure 'Child Care Payroll Employment YoY % Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Payroll Employment YoY %],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		lineageTag: ae0a3d79-9797-463d-9814-ce45211fbeb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Payroll Employment YoY % Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [All Industries Payroll Employment YoY %],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		lineageTag: 4b135a7b-cd79-4582-b130-f05571689af8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Share of Payroll Employment Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Share of Payroll Employment],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		lineageTag: 40626bd7-82e1-4a52-b05b-8647a87f7fd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Payroll Employment 2019 Avg' =
			
			CALCULATE (
			    AVERAGEX (
			        VALUES ( 'Date'[Year] ),
			        [Child Care Payroll Employment]
			    ),
			    FILTER (
			        ALL ( 'Date' ),
			        'Date'[Year] = 2019
			    )
			)
		lineageTag: 0709d4e7-b18f-41d5-8a91-5bb2bf752df9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Payroll Employment 2019 Avg' =
			
			CALCULATE (
			    AVERAGEX (
			        VALUES ( 'Date'[Year] ),
			        [All Industries Payroll Employment]
			    ),
			    FILTER (
			        ALL ( 'Date' ),
			        'Date'[Year] = 2019
			    )
			)
		lineageTag: 27ad0504-a54a-41a4-a04b-fc1e1de42c4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Payroll Employment Index 2019' =
			
			DIVIDE (
			    [Child Care Payroll Employment],
			    [Child Care Payroll Employment 2019 Avg]
			) * 100
		lineageTag: 42f9c84f-8f87-4ba2-8890-477175045619

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Payroll Employment Index 2019' =
			
			DIVIDE (
			    [All Industries Payroll Employment],
			    [All Industries Payroll Employment 2019 Avg]
			) * 100
		lineageTag: bd35ef25-f10e-4477-8be3-bc4f0454a85a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Payroll Employment 3-Year Average' =
			
			AVERAGEX (
			    DATESINPERIOD (
			        'Date'[Date],
			        MAX ( 'Date'[Date] ),
			        -3,
			        YEAR
			    ),
			    [Child Care Payroll Employment]
			)
		lineageTag: 6d7da4ec-a04a-495f-b111-ed94f4fda032

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Payroll Employment 3-Year Average' =
			
			AVERAGEX (
			    DATESINPERIOD (
			        'Date'[Date],
			        MAX ( 'Date'[Date] ),
			        -3,
			        YEAR
			    ),
			    [All Industries Payroll Employment]
			)
		lineageTag: a3181cc5-1b8d-407e-afe4-12781168c922

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 527b56ca-eee7-4867-8e27-a0d258212b71
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GEO
		dataType: string
		lineageTag: 9297fa99-29a0-497c-9800-1b6c3d114499
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Employee Type'
		dataType: string
		lineageTag: 7c9029eb-b5c3-4f8d-a307-d263aae4e34c
		summarizeBy: none
		sourceColumn: Employee Type

		annotation SummarizationSetBy = Automatic

	column NAICS
		dataType: string
		lineageTag: a5ee0061-432b-4c7e-b6d5-fd661521c9a9
		summarizeBy: none
		sourceColumn: NAICS

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 849305b3-13f2-4394-aa66-0a907f0cb503
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: int64
		formatString: 0
		lineageTag: fd992517-833b-42cc-833a-1ce618ab7838
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

	partition 'SEPH Employment' = m
		mode: import
		source =
				let
				  Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100202-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", type text}, {"GEO", type text}, {"DGUID", type text}, {"Type of employee", type text}, {"North American Industry Classification System (NAICS)", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", Int64.Type}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"DGUID", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Type of employee", "Employee Type"}, {"North American Industry Classification System (NAICS)", "NAICS"}}),
				    #"Added Date" = Table.AddColumn(#"Renamed Columns", "Date", each Date.FromText([REF_DATE] & "-01-01"), type date),
                    #"Removed Columns1" = Table.RemoveColumns(#"Added Date",{"REF_DATE"})
                in
                  #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table




