table 'SEPH Weekly Earnings'
	lineageTag: 0dfc7f33-5f18-4e27-9a17-f681433f197f

	measure 'Weekly Earnings Value' =
			
			MAX ( 'SEPH Weekly Earnings'[VALUE] )
		lineageTag: 3c7354a8-c4b7-4497-b2d5-06239384265a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Avg Weekly Earnings' =
			
			CALCULATE (
			    [Weekly Earnings Value],
			    'SEPH Weekly Earnings'[NAICS] = "Child day-care services [6244]",
			    'SEPH Weekly Earnings'[Employee Type] = "All employees",
			    'SEPH Weekly Earnings'[Overtime] = "Including overtime"
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1aec9f2f-c6ef-4e0e-b073-54844d595c0c

	measure 'All Industries Avg Weekly Earnings' =
			
			CALCULATE (
			    [Weekly Earnings Value],
			    'SEPH Weekly Earnings'[NAICS] = "Industrial aggregate excluding unclassified businesses [11-91N]",
			    'SEPH Weekly Earnings'[Employee Type] = "All employees",
			    'SEPH Weekly Earnings'[Overtime] = "Including overtime"
			)
		lineageTag: 660cf5a4-4135-4141-be76-a79495ae3294

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Weekly Earnings Gap' =
			
			[Child Care Avg Weekly Earnings] - [All Industries Avg Weekly Earnings]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 180bde68-0948-47de-8de4-e842bd81edba

	measure 'Child Care Weekly Earnings Relative to All Industries' =
			
			DIVIDE (
			    [Child Care Avg Weekly Earnings],
			    [All Industries Avg Weekly Earnings]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7ce0f669-46c8-4640-a704-db79e966deb4

	measure 'Child Care Weekly Earnings YoY %' =
			
			VAR CurrentValue = [Child Care Avg Weekly Earnings]
			VAR PreviousValue =
			    CALCULATE (
			        [Child Care Avg Weekly Earnings],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			RETURN
			    DIVIDE ( CurrentValue - PreviousValue, PreviousValue )
		lineageTag: 8b1de22f-443d-4d96-bc76-238e22e89fd4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Weekly Earnings YoY %' =
			
			VAR CurrentValue = [All Industries Avg Weekly Earnings]
			VAR PreviousValue =
			    CALCULATE (
			        [All Industries Avg Weekly Earnings],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			RETURN
			    DIVIDE ( CurrentValue - PreviousValue, PreviousValue )
		lineageTag: b30f6d96-e4b4-4052-ae20-72e3e403ea79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Weekly Earnings YoY % Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Weekly Earnings YoY %],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		formatString: 0.0%;-0.0%;0.0%

	measure 'All Industries Weekly Earnings YoY % Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [All Industries Weekly Earnings YoY %],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		formatString: 0.0%;-0.0%;0.0%
	measure 'Child Care Weekly Earnings Relative Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Weekly Earnings Relative to All Industries],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		lineageTag: 88d0e841-d1bc-4a80-ace0-67df167b4bd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Weekly Earnings Gap Latest' =
			
			VAR LatestYear = [Latest SEPH Year]
			RETURN
			    CALCULATE (
			        [Child Care Weekly Earnings Gap],
			        FILTER (
			            ALL ( 'Date'[Date] ),
			            'Date'[Date] = LatestYear
			        )
			    )
		lineageTag: 0be6d5b2-9b71-4760-b862-eea3ccd030c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Weekly Earnings 2019 Avg' =
			
			CALCULATE (
			    AVERAGEX (
			        VALUES ( 'Date'[Year] ),
			        [Child Care Avg Weekly Earnings]
			    ),
			    FILTER (
			        ALL ( 'Date' ),
			        'Date'[Year] = 2019
			    )
			)
		lineageTag: 21499c23-c346-4f9f-a3a8-abfce0da240a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Industries Weekly Earnings 2019 Avg' =
			
			CALCULATE (
			    AVERAGEX (
			        VALUES ( 'Date'[Year] ),
			        [All Industries Avg Weekly Earnings]
			    ),
			    FILTER (
			        ALL ( 'Date' ),
			        'Date'[Year] = 2019
			    )
			)
		lineageTag: 72af607c-7b38-42f9-ae43-24c078f37b53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Child Care Weekly Earnings Index 2019' =
			DIVIDE (
			    [Child Care Avg Weekly Earnings],
			    [Child Care Weekly Earnings 2019 Avg]
			) * 100
		formatString: 0.0
		lineageTag: 29860063-b4a5-46df-afa1-45e432df4d83

	measure 'All Industries Weekly Earnings Index 2019' =
			DIVIDE (
			    [All Industries Avg Weekly Earnings],
			    [All Industries Weekly Earnings 2019 Avg]
			) * 100
		formatString: 0.0
		lineageTag: a095a8aa-7c39-4e68-a4c0-1b7d9eb5f63c

	measure 'Child Care Avg Weekly Earnings 3-Year Average' =
			
			AVERAGEX (
			    DATESINPERIOD (
			        'Date'[Date],
			        MAX ( 'Date'[Date] ),
			        -3,
			        YEAR
			    ),
			    [Child Care Avg Weekly Earnings]
			)
		lineageTag: 1e79f040-d71a-46f7-917f-25ee146f9807

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 14737e7c-2ee1-42cf-a76a-d87130ba7c52
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GEO
		dataType: string
		lineageTag: bba31fea-8730-4d2c-a458-f76f225eb630
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column 'Employee Type'
		dataType: string
		lineageTag: 2131f6d0-6e2f-475f-9c4a-736530a3ca7d
		summarizeBy: none
		sourceColumn: Employee Type

		annotation SummarizationSetBy = Automatic

	column Overtime
		dataType: string
		lineageTag: 34fd60bd-b613-4329-aa6d-22db5ed8b1c3
		summarizeBy: none
		sourceColumn: Overtime

		annotation SummarizationSetBy = Automatic

	column NAICS
		dataType: string
		lineageTag: 24211653-a411-494e-86ce-80c2e1b3afd9
		summarizeBy: none
		sourceColumn: NAICS

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: f9abfd45-e7c1-4d70-ad6a-0d62bbec8d47
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: d8b0356c-cdfb-4ff6-b8ca-11b5560770d0
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'SEPH Weekly Earnings' = m
		mode: import
		source =
				let
				  Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100204-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", type text}, {"GEO", type text}, {"DGUID", type text}, {"Type of employees", type text}, {"Overtime", type text}, {"North American Industry Classification System (NAICS)", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"DGUID", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Type of employees", "Employee Type"}, {"North American Industry Classification System (NAICS)", "NAICS"}}),
                    #"Added Date" = Table.AddColumn(#"Renamed Columns", "Date", each Date.FromText([REF_DATE] & "-01-01"), type date),
                    #"Removed Columns1" = Table.RemoveColumns(#"Added Date",{"REF_DATE"})
                in
                  #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table





