table 'Work Absence'
	lineageTag: 8180e8f6-053f-42cb-b6a8-6d9f5543174a

	measure 'Absence Value' =
			
			AVERAGE ( 'Work Absence'[VALUE] )
		formatString: 0.0
		lineageTag: 1748afbd-0d19-4b68-aad4-8c5967649b7a

	measure 'Absence Latest Year' =
			
			VAR _LatestYear = [Latest Year]
			RETURN
			    CALCULATE (
			        AVERAGE ( 'Work Absence'[VALUE] ),
			        REMOVEFILTERS ( 'Work Absence'[Year] ),
			        'Work Absence'[Year] = _LatestYear
			    )
		formatString: 0.0
		lineageTag: 22b73b5e-ff25-444e-8208-e713bc36239c

	measure 'Absence Previous Year' =
			
			VAR _LatestYear = [Latest Year]
			RETURN
			    CALCULATE (
			        AVERAGE ( 'Work Absence'[VALUE] ),
			        REMOVEFILTERS ( 'Work Absence'[Year] ),
			        'Work Absence'[Year] = _LatestYear - 1
			    )
		lineageTag: be37dddb-643f-469b-abef-8abb5ee52a1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Absence YoY Change' =
			
			[Absence Latest Year] - [Absence Previous Year]
		formatString: 0.0
		lineageTag: 007bf002-b67d-476d-8202-39f347292f9b

	measure 'Absence 2019' =
			
			CALCULATE (
			    AVERAGE ( 'Work Absence'[VALUE] ),
			    REMOVEFILTERS ( 'Work Absence'[Year] ),
			    'Work Absence'[Year] = 2019
			)
		lineageTag: dd143475-93f2-4c70-a4b0-b49b27bb1ecc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Absence Change Since 2019' =
			
			[Absence Latest Year] - [Absence 2019]
		formatString: 0.0
		lineageTag: 9b4bb3a5-fd97-420e-adb1-056eb5a4cd51

	measure 'Absence Annual Value' =
			
			AVERAGE ( 'Work Absence'[VALUE] )
		formatString: 0.0
		lineageTag: ba4b6840-9d54-4bd9-878e-471fb2e427e6

	column REF_DATE
		dataType: int64
		formatString: 0
		lineageTag: 9df3350d-f73d-4cfd-8440-82d936ce2fab
		summarizeBy: sum
		sourceColumn: REF_DATE

		annotation SummarizationSetBy = Automatic

	column GEO
		dataType: string
		lineageTag: b5cf7f21-d36c-4ba2-9512-9b92c434eb22
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column DGUID
		dataType: string
		lineageTag: c4056291-d92e-4185-9982-023234d2811a
		summarizeBy: none
		sourceColumn: DGUID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 4bbeb2d3-421e-4143-a8b2-54823deb4c72
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Presence of children'
		dataType: string
		lineageTag: 6bd48a08-60e7-46e0-bcf7-14fa40a88d55
		summarizeBy: none
		sourceColumn: Presence of children

		annotation SummarizationSetBy = Automatic

	column 'Work absence statistics'
		dataType: string
		lineageTag: e8cc38fc-c5fe-4683-a983-15ab9911a09b
		summarizeBy: none
		sourceColumn: Work absence statistics

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 0ce4af89-0748-4c30-8de8-b2d2d1f45f96
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: 1b625bd1-d03e-4577-9c92-cb884cc94892
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year = VALUE ( 'Work Absence'[REF_DATE] )
		dataType: int64
		lineageTag: 45f47a8e-e363-46dd-8064-aea605bf5526
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Work Absence' = m
		mode: import
		source =
				let
				  Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100194-eng.zip"),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", Int64.Type}, {"GEO", type text}, {"DGUID", type text}, {"Gender", type text}, {"Presence of children", type text}, {"Work absence statistics", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "STATUS", "SYMBOL", "TERMINATED", "DECIMALS"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

