table 14100062-eng
	lineageTag: 09d6f483-c294-4d78-8321-d793b4e51404

	column REF_DATE
		dataType: int64
		formatString: 0
		lineageTag: d80da6d8-d884-4c84-b32c-7d27ff3eee65
		summarizeBy: sum
		sourceColumn: REF_DATE

		annotation SummarizationSetBy = Automatic

	column GEO
		dataType: string
		lineageTag: 0473946e-4bf1-4c4c-b68c-cc04c14cdd19
		summarizeBy: none
		sourceColumn: GEO

		annotation SummarizationSetBy = Automatic

	column Wages
		dataType: string
		lineageTag: 9db5964b-f30a-44f8-9eb9-8fd4bc9c9668
		summarizeBy: none
		sourceColumn: Wages

		annotation SummarizationSetBy = Automatic

	column 'Type of work'
		dataType: string
		lineageTag: 1eeac547-1673-4de8-9360-be804bdb5c22
		summarizeBy: none
		sourceColumn: Type of work

		annotation SummarizationSetBy = Automatic

	column 'National Occupational Classification for Statistics (NOC-S)'
		dataType: string
		lineageTag: 58375d9f-c675-4d1b-b3c0-635e2ab35dd8
		summarizeBy: none
		sourceColumn: National Occupational Classification for Statistics (NOC-S)

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 8930219d-6040-48c1-9185-49468a925989
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column 'Age group'
		dataType: string
		lineageTag: 1b3407e7-a5ac-4638-8ca6-fea7dd2b705b
		summarizeBy: none
		sourceColumn: Age group

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: 2987f2c1-4e1b-407e-b3da-dc7034aa72b6
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		type: calculated
		lineageTag: 61d9617b-de35-44b2-bc52-8b84646327c7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	partition 14100062-eng = m
		mode: import
		source =
				let
				    Source = Web.Contents("https://www150.statcan.gc.ca/n1/tbl/csv/14100062-eng.zip "),
				    Custom1 = Unzip(Source),
				    Content = Custom1{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REF_DATE", Int64.Type}, {"GEO", type text}, {"DGUID", type text}, {"Wages", type text}, {"Type of work", type text}, {"National Occupational Classification for Statistics (NOC-S)", type text}, {"Sex", type text}, {"Age group", type text}, {"UOM", type text}, {"UOM_ID", Int64.Type}, {"SCALAR_FACTOR", type text}, {"SCALAR_ID", Int64.Type}, {"VECTOR", type text}, {"COORDINATE", type text}, {"VALUE", type number}, {"STATUS", type text}, {"SYMBOL", type text}, {"TERMINATED", type text}, {"DECIMALS", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"STATUS", "SYMBOL", "TERMINATED", "DECIMALS", "UOM", "UOM_ID", "SCALAR_FACTOR", "SCALAR_ID", "VECTOR", "COORDINATE", "DGUID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

