table 'ECE Monthly'
	lineageTag: e5371164-20e6-48d2-aec2-6864f760e998

	measure 'Monthly Latest Date' = ```
			
			MAX ( 'ECE Monthly'[Date] )
			
			```
		formatString: General Date
		lineageTag: 2c2a7801-1f96-4598-b0f4-c1eb8e80aa82

	measure 'Monthly Estimate Value' = ```
			
			CALCULATE (
			    SUM ( 'ECE Monthly'[Estimate] ),
			    TREATAS ( VALUES ( ECE[Province] ), 'ECE Monthly'[Province] ),
			    TREATAS ( VALUES ( ECE[Occupation] ), 'ECE Monthly'[Occupation] ),
			    TREATAS ( VALUES ( ECE[Variable] ), 'ECE Monthly'[Variable] )
			)
			
			```
		lineageTag: b61e45c5-36d0-47ca-93dc-f92be38d87b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Employment' = ```
			
			CALCULATE (
			    [Monthly Estimate Value],
			    'ECE Monthly'[Variable] = "Employment"
			)
			
			```
		lineageTag: 64c42fdc-32ea-4bea-a8cb-d727fc58efdb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Estimate Value (Latest)' = ```
			
			VAR d = [Monthly Latest Date]
			RETURN
			CALCULATE ( [Monthly Estimate Value], DateTable[Date] = d )
			
			```
		lineageTag: d10c97a8-9804-4412-abb9-af691035612b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Employment (Latest)' = ```
			
			VAR d = [Monthly Latest Date]
			RETURN
			CALCULATE ( [Monthly Employment], DateTable[Date] = d )
			
			```
		lineageTag: 3ff6d289-6f9c-4f5e-804f-48c96c0eb460

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Estimate Value (MoM)' = ```
			
			[Monthly Estimate Value]
			    - CALCULATE (
			        [Monthly Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			
			```
		lineageTag: e2a703c6-05be-42e4-b99e-2d23327ec4b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Estimate Value (MoM %)' = ```
			
			DIVIDE (
			    [Monthly Estimate Value (MoM)],
			    CALCULATE (
			        [Monthly Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 87698a68-efe8-4ade-a3f7-7b0e3dd0b76f

	measure 'Monthly Estimate Value (YoY)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Monthly Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        [Monthly Estimate Value] - _PreviousYearValue
			    )
			
			```
		lineageTag: fc4c72e4-974a-4eee-afa9-dd729028262a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Estimate Value (YoY %)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Monthly Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        DIVIDE ( [Monthly Estimate Value] - _PreviousYearValue, _PreviousYearValue )
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7b3b3a3a-cf9c-4be5-accd-42af1d99926c

	measure 'Monthly Employment (MoM)' = ```
			
			[Monthly Employment]
			    - CALCULATE (
			        [Monthly Employment],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			
			```
		lineageTag: 378b35a2-db53-4c4a-9bb9-6b7aa613c295

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Employment (MoM %)' = ```
			
			DIVIDE (
			    [Monthly Employment (MoM)],
			    CALCULATE (
			        [Monthly Employment],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ee4b5756-7e2a-4114-a3a3-f02ab1f0ed1e

	measure 'Monthly Employment (YoY)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Monthly Employment],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        [Monthly Employment] - _PreviousYearValue
			    )
			
			```
		lineageTag: 307553b3-8b0e-4578-9016-4f527f96e45c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Employment (YoY %)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Monthly Employment],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        DIVIDE ( [Monthly Employment] - _PreviousYearValue, _PreviousYearValue )
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7d854b6f-e709-407e-89c2-12c3f4cf6484

	column 'Reference Period'
		dataType: int64
		formatString: 0
		lineageTag: 4751bd36-32df-44c9-b496-6a0d30e1da99
		summarizeBy: sum
		sourceColumn: Reference Period

		annotation SummarizationSetBy = Automatic

	column Province
		dataType: string
		lineageTag: 4778310b-31c7-4cb6-bd79-ff61b9d1b9f4
		summarizeBy: none
		sourceColumn: Province

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 93fe6391-3151-43e4-81bf-a2025e60dba3
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Variable
		dataType: string
		lineageTag: dc585ffd-e330-4ebd-b9fe-fabd8a4e1df6
		summarizeBy: none
		sourceColumn: Variable

		annotation SummarizationSetBy = Automatic

	column Estimate
		dataType: double
		lineageTag: 425c0d3a-df02-4e7b-93b2-357007f1e066
		summarizeBy: sum
		sourceColumn: Estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coefficient ofvariation (%) ofestimate6'
		dataType: double
		lineageTag: f5c6ae98-5951-4245-ba4c-c8d5c7117381
		summarizeBy: sum
		sourceColumn: Coefficient ofvariation (%) ofestimate6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Standard error ofestimate'
		dataType: double
		lineageTag: 7a1c3286-afc9-4ad7-bbe1-71953879ac8a
		summarizeBy: sum
		sourceColumn: Standard error ofestimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lower bound (95%CI) of estimate'
		dataType: double
		lineageTag: e5d12da0-06c4-4267-9cd9-ff9dce4f25bf
		summarizeBy: sum
		sourceColumn: Lower bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper bound (95%CI) of estimate'
		dataType: double
		lineageTag: 31d796ab-be92-48dd-8e31-ff422cfe70bc
		summarizeBy: sum
		sourceColumn: Upper bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 116adbef-9b47-4fe6-be46-5292063c7f2d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 403d5a15-a766-405d-8585-bc9faed4d3c2
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: ad91ccce-effa-4c93-ba8e-c50f1f28f1bf
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b543ea45-ed56-47da-8479-99a14dd493ff
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Source Sheet'
		dataType: string
		lineageTag: ab010b2c-e34d-4836-8293-e8d6803595d4
		summarizeBy: none
		sourceColumn: Source Sheet

		annotation SummarizationSetBy = Automatic

	column 'Source Table'
		dataType: string
		lineageTag: 3d5693d3-11c8-448b-8c08-8d2ba62b47fc
		summarizeBy: none
		sourceColumn: Source Table

		annotation SummarizationSetBy = Automatic

	column 'Table Title'
		dataType: string
		lineageTag: 7f718095-87ba-4d3a-9130-d575f6af1da1
		summarizeBy: none
		sourceColumn: Table Title

		annotation SummarizationSetBy = Automatic

	column 'Series Type'
		dataType: string
		lineageTag: fa3522eb-65a8-489a-a94c-47ed6b4c5e9a
		summarizeBy: none
		sourceColumn: Series Type

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: a5696d73-251a-435a-8c0b-e021b9bb54bf
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column 'NOC Detail'
		dataType: string
		lineageTag: 8fd25be5-4602-4493-868b-a10ee04d52c2
		summarizeBy: none
		sourceColumn: NOC Detail

		annotation SummarizationSetBy = Automatic

	column 'NOC Code'
		dataType: string
		lineageTag: 22b47c7e-3996-41f7-b21f-cd16063eaa1a
		summarizeBy: none
		sourceColumn: NOC Code

		annotation SummarizationSetBy = Automatic

	column 'NOC Title'
		dataType: string
		lineageTag: 03833a69-a574-4e63-8966-686520346f05
		summarizeBy: none
		sourceColumn: NOC Title

		annotation SummarizationSetBy = Automatic

	column 'Is Suppressed'
		dataType: boolean
		lineageTag: fba0c2c8-47fb-4062-a3ba-9d4458bf077a
		summarizeBy: none
		sourceColumn: Is Suppressed

		annotation SummarizationSetBy = Automatic

	partition 'ECE Monthly' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MLOUI\OneDrive\Work\PBI DATA FILES\Monthly ECE ETL Pipeline for PBI\Monthly ECE ETL Pipeline for PBI\03_Output_PowerBI\historical_ece_data_powerbi.csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_sheet", type text}, {"source_table", type text}, {"table_title", type text}, {"series_type", type text}, {"frequency", type text}, {"noc_detail", type text}, {"reference_period", Int64.Type}, {"reference_date", type date}, {"year", Int64.Type}, {"month", Int64.Type}, {"province", type text}, {"occupation_5digit_noc", type text}, {"noc_code", type text}, {"noc_title", type text}, {"variable", type text}, {"estimate", type number}, {"coefficient_of_variation_percent", type number}, {"standard_error", type number}, {"lower_bound_95_ci", type number}, {"upper_bound_95_ci", type number}, {"is_suppressed", type logical}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [source_table] = "Table 3" and [frequency] = "Monthly" and [series_type] = "monthly_separate_nocs"),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"reference_period", "Reference Period"}, {"province", "Province"}, {"occupation_5digit_noc", "Occupation"}, {"variable", "Variable"}, {"estimate", "Estimate"}, {"coefficient_of_variation_percent", "Coefficient ofvariation (%) ofestimate6"}, {"standard_error", "Standard error ofestimate"}, {"lower_bound_95_ci", "Lower bound (95%CI) of estimate"}, {"upper_bound_95_ci", "Upper bound (95%CI) of estimate"}, {"reference_date", "Date"}, {"year", "Year"}, {"month", "Month"}, {"source_sheet", "Source Sheet"}, {"source_table", "Source Table"}, {"table_title", "Table Title"}, {"series_type", "Series Type"}, {"frequency", "Frequency"}, {"noc_detail", "NOC Detail"}, {"noc_code", "NOC Code"}, {"noc_title", "NOC Title"}, {"is_suppressed", "Is Suppressed"}}),
				    #"Inserted Month Name" = Table.AddColumn(#"Renamed Columns", "Month Name", each Date.MonthName([Date]), type text)
				in
				    #"Inserted Month Name"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

