table ECE
	lineageTag: d4003961-5fcd-4ae6-9531-5c542bbfaeb1

	measure 'Latest Date' = ```
			
			MAX ( DateTable[Date] )
			
			```
		formatString: General Date
		lineageTag: a350be79-3bce-426d-b24e-379997660354

	measure 'Estimate Value' = ```
			
			SUM ( ECE[Estimate] )
			
			```
		lineageTag: e25bcfeb-9d05-448a-9d3d-7161b7f9a0c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value], DateTable[Date] = d )
			
			```
		lineageTag: 81fed9d5-47ee-4c09-b055-31e30f5143ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (YoY)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        [Estimate Value] - _PreviousYearValue
			    )
			
			```
		lineageTag: 28f28ec2-79ee-4f43-82c1-c63ad78a8011

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (YoY %)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        DIVIDE ( [Estimate Value] - _PreviousYearValue, _PreviousYearValue )
			    )
			
			```
		lineageTag: cfb80744-2c0c-41f5-8de8-f8e0c73bf249

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (MoM)' = ```
			
			[Estimate Value]
			    - CALCULATE (
			        [Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			
			```
		lineageTag: 9adb30c7-86b8-4524-befd-2fd2d353b7a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (MoM %)' = ```
			
			DIVIDE (
			    [Estimate Value (MoM)],
			    CALCULATE (
			        [Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 474ffc8e-4959-4533-874f-b19575e6c13d

	measure 'Estimate Value (Latest MoM)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (MoM)], DateTable[Date] = d )
			
			```
		lineageTag: 493ebd48-702d-42b6-8f6c-9f20ab131949

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest MoM %)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (MoM %)], DateTable[Date] = d )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3e66f9ec-c38d-4119-84cd-54678c2bfa2a

	measure 'Estimate Value (Prev Month)' = ```
			
			CALCULATE (
			    [Estimate Value],
			    DATEADD ( DateTable[Date], -1, MONTH )
			)
			
			```
		lineageTag: 8fe4ae51-0d00-456f-ad38-1ebcc9615b8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest YoY)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (YoY)], DateTable[Date] = d )
			
			```
		lineageTag: 709b1b39-1cbd-4134-a395-25eff1d30b0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest YoY %)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (YoY %)], DateTable[Date] = d )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 788342c9-efe3-436e-93de-f5e03a3c9f94

	column 'Reference Period'
		dataType: int64
		formatString: 0
		lineageTag: ffa70e13-da35-4200-9d8a-86da5c8a1e2d
		summarizeBy: sum
		sourceColumn: Reference Period

		annotation SummarizationSetBy = Automatic

	column Province
		dataType: string
		lineageTag: 0511a280-b71e-45cb-8f7d-5585782a16ae
		summarizeBy: none
		sourceColumn: Province

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 6ba748f3-de76-417e-9ba9-6e3c926474f0
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Variable
		dataType: string
		lineageTag: 843c6af2-6cc4-4a79-a200-a6f4803ede16
		summarizeBy: none
		sourceColumn: Variable

		annotation SummarizationSetBy = Automatic

	column Estimate
		dataType: double
		lineageTag: 1499da1b-bf2b-4c9d-8fe3-02dba3e999f2
		summarizeBy: sum
		sourceColumn: Estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coefficient ofvariation (%) ofestimate6'
		dataType: double
		lineageTag: ffb2b24f-3ea2-41bd-9833-418c114cf3d2
		summarizeBy: sum
		sourceColumn: Coefficient ofvariation (%) ofestimate6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Standard error ofestimate'
		dataType: double
		lineageTag: 54aea7a1-d494-43a7-8fbb-b5d07a32360d
		summarizeBy: sum
		sourceColumn: Standard error ofestimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lower bound (95%CI) of estimate'
		dataType: double
		lineageTag: dae46d48-07f7-43ec-adf3-8c0d36ffed2b
		summarizeBy: sum
		sourceColumn: Lower bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper bound (95%CI) of estimate'
		dataType: double
		lineageTag: d66291e7-337c-46c0-ad9e-385ebdc50049
		summarizeBy: sum
		sourceColumn: Upper bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72860bce-83a3-418a-a890-b46842951143
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3c273d89-3ca3-40a4-956d-c4bed8d312ce
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 293648f6-9562-482c-ac50-4f3d07161b20
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b1a205fa-8d03-4796-a662-1ea021740c17
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition ECE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MLOUI\OneDrive\Work\PBI\PBI DATA FILES\ECE\Historical ECE data.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Reference Period", Int64.Type}, {"Province", type text}, {"Occupation (5-digit NOC)", type text}, {"Variable", type text}, {"Estimate (rounded)5", type number}, {"Coefficient of#(lf)variation (%) of#(lf)estimate6", type number}, {"Standard error of#(lf)estimate", type number}, {"Lower bound (95%#(lf)CI) of estimate", type number}, {"Upper bound (95%#(lf)CI) of estimate", type number}, {"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Estimate (rounded)5", "Estimate"}, {"Occupation (5-digit NOC)", "Occupation"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Custom", each Date.FromText(Text.Start(Text.From([Reference Period]),4) & "-" & Text.End(Text.From([Reference Period]),2) & "-01")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Custom", "Date"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type1", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([Date]), Int64.Type)
				in
				    #"Inserted Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

