table ECE
	lineageTag: d4003961-5fcd-4ae6-9531-5c542bbfaeb1

	measure 'Latest Date' = ```
			
			MAX ( DateTable[Date] )
			
			```
		formatString: General Date
		lineageTag: a350be79-3bce-426d-b24e-379997660354

	measure 'Estimate Value' = ```
			
			SUM ( ECE[Estimate] )
			
			```
		lineageTag: e25bcfeb-9d05-448a-9d3d-7161b7f9a0c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value], DateTable[Date] = d )
			
			```
		lineageTag: 81fed9d5-47ee-4c09-b055-31e30f5143ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (YoY)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        [Estimate Value] - _PreviousYearValue
			    )
			
			```
		lineageTag: 28f28ec2-79ee-4f43-82c1-c63ad78a8011

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (YoY %)' = ```
			
			VAR _PreviousYearValue =
			    CALCULATE (
			        [Estimate Value],
			        SAMEPERIODLASTYEAR ( DateTable[Date] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _PreviousYearValue ),
			        BLANK (),
			        DIVIDE ( [Estimate Value] - _PreviousYearValue, _PreviousYearValue )
			    )
			
			```
		lineageTag: cfb80744-2c0c-41f5-8de8-f8e0c73bf249

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (MoM)' = ```
			
			[Estimate Value]
			    - CALCULATE (
			        [Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			
			```
		lineageTag: 9adb30c7-86b8-4524-befd-2fd2d353b7a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (MoM %)' = ```
			
			DIVIDE (
			    [Estimate Value (MoM)],
			    CALCULATE (
			        [Estimate Value],
			        DATEADD ( DateTable[Date], -1, MONTH )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 474ffc8e-4959-4533-874f-b19575e6c13d

	measure 'Estimate Value (Latest MoM)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (MoM)], DateTable[Date] = d )
			
			```
		lineageTag: 493ebd48-702d-42b6-8f6c-9f20ab131949

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest MoM %)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (MoM %)], DateTable[Date] = d )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3e66f9ec-c38d-4119-84cd-54678c2bfa2a

	measure 'Estimate Value (Prev Month)' = ```
			
			CALCULATE (
			    [Estimate Value],
			    DATEADD ( DateTable[Date], -1, MONTH )
			)
			
			```
		lineageTag: 8fe4ae51-0d00-456f-ad38-1ebcc9615b8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest YoY)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (YoY)], DateTable[Date] = d )
			
			```
		lineageTag: 709b1b39-1cbd-4134-a395-25eff1d30b0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Estimate Value (Latest YoY %)' = ```
			
			VAR d = [Latest Date]
			RETURN
			CALCULATE ( [Estimate Value (YoY %)], DateTable[Date] = d )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 788342c9-efe3-436e-93de-f5e03a3c9f94

	measure '3MMA Estimate Value' = ```
			
			[Estimate Value]
			
			```
		lineageTag: f275e1bb-9f8e-46c5-9e38-dcb939c7bbd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '3MMA Employment' = ```
			
			CALCULATE (
			    [3MMA Estimate Value],
			    ECE[Variable] = "Employment"
			)
			
			```
		lineageTag: 47cafc6d-c414-4594-ab56-0ba87a10bef3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '3MMA Estimate Value (YoY)' = ```
			
			[Estimate Value (YoY)]
			
			```
		lineageTag: 965738a4-ea75-45cb-851c-ef0507445112

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Reference Period'
		dataType: int64
		formatString: 0
		lineageTag: ffa70e13-da35-4200-9d8a-86da5c8a1e2d
		summarizeBy: sum
		sourceColumn: Reference Period

		annotation SummarizationSetBy = Automatic

	column Province
		dataType: string
		lineageTag: 0511a280-b71e-45cb-8f7d-5585782a16ae
		summarizeBy: none
		sourceColumn: Province

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 6ba748f3-de76-417e-9ba9-6e3c926474f0
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Variable
		dataType: string
		lineageTag: 843c6af2-6cc4-4a79-a200-a6f4803ede16
		summarizeBy: none
		sourceColumn: Variable

		annotation SummarizationSetBy = Automatic

	column Estimate
		dataType: double
		lineageTag: 1499da1b-bf2b-4c9d-8fe3-02dba3e999f2
		summarizeBy: sum
		sourceColumn: Estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coefficient ofvariation (%) ofestimate6'
		dataType: double
		lineageTag: ffb2b24f-3ea2-41bd-9833-418c114cf3d2
		summarizeBy: sum
		sourceColumn: Coefficient ofvariation (%) ofestimate6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Standard error ofestimate'
		dataType: double
		lineageTag: 54aea7a1-d494-43a7-8fbb-b5d07a32360d
		summarizeBy: sum
		sourceColumn: Standard error ofestimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lower bound (95%CI) of estimate'
		dataType: double
		lineageTag: dae46d48-07f7-43ec-adf3-8c0d36ffed2b
		summarizeBy: sum
		sourceColumn: Lower bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper bound (95%CI) of estimate'
		dataType: double
		lineageTag: d66291e7-337c-46c0-ad9e-385ebdc50049
		summarizeBy: sum
		sourceColumn: Upper bound (95%CI) of estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72860bce-83a3-418a-a890-b46842951143
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3c273d89-3ca3-40a4-956d-c4bed8d312ce
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 293648f6-9562-482c-ac50-4f3d07161b20
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b1a205fa-8d03-4796-a662-1ea021740c17
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Source Sheet'
		dataType: string
		lineageTag: 32bedbaf-901f-4660-85c7-940dbf44d9c3
		summarizeBy: none
		sourceColumn: Source Sheet

		annotation SummarizationSetBy = Automatic

	column 'Source Table'
		dataType: string
		lineageTag: 0de7af22-0a63-42e0-a9de-89071f3d1618
		summarizeBy: none
		sourceColumn: Source Table

		annotation SummarizationSetBy = Automatic

	column 'Table Title'
		dataType: string
		lineageTag: 9696ac29-e017-471b-9aec-3267c2ec407b
		summarizeBy: none
		sourceColumn: Table Title

		annotation SummarizationSetBy = Automatic

	column 'Series Type'
		dataType: string
		lineageTag: 6e628bec-5c46-4943-b07f-d2bd850d96ed
		summarizeBy: none
		sourceColumn: Series Type

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: da3d94c1-40dc-4963-bbab-616a94d81b7b
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column 'NOC Detail'
		dataType: string
		lineageTag: ee31fb27-2137-492f-bdf5-32e27a44ae64
		summarizeBy: none
		sourceColumn: NOC Detail

		annotation SummarizationSetBy = Automatic

	column 'NOC Code'
		dataType: string
		lineageTag: e97dd5b9-d433-4174-a373-3711b0b66cfb
		summarizeBy: none
		sourceColumn: NOC Code

		annotation SummarizationSetBy = Automatic

	column 'NOC Title'
		dataType: string
		lineageTag: ed072565-4b3f-42cf-ba62-6f45fa926cc3
		summarizeBy: none
		sourceColumn: NOC Title

		annotation SummarizationSetBy = Automatic

	column 'Is Suppressed'
		dataType: boolean
		lineageTag: dc7b400b-a803-4af7-a623-fac6ff4e1406
		summarizeBy: none
		sourceColumn: Is Suppressed

		annotation SummarizationSetBy = Automatic

	partition ECE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MLOUI\OneDrive\Work\PBI DATA FILES\Monthly ECE ETL Pipeline for PBI\Monthly ECE ETL Pipeline for PBI\03_Output_PowerBI\historical_ece_data_powerbi.csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_sheet", type text}, {"source_table", type text}, {"table_title", type text}, {"series_type", type text}, {"frequency", type text}, {"noc_detail", type text}, {"reference_period", Int64.Type}, {"reference_date", type date}, {"year", Int64.Type}, {"month", Int64.Type}, {"province", type text}, {"occupation_5digit_noc", type text}, {"noc_code", type text}, {"noc_title", type text}, {"variable", type text}, {"estimate", type number}, {"coefficient_of_variation_percent", type number}, {"standard_error", type number}, {"lower_bound_95_ci", type number}, {"upper_bound_95_ci", type number}, {"is_suppressed", type logical}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [source_table] = "Table 2" and [frequency] = "3MMA" and [series_type] = "three_month_moving_average_separate_nocs"),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"reference_period", "Reference Period"}, {"province", "Province"}, {"occupation_5digit_noc", "Occupation"}, {"variable", "Variable"}, {"estimate", "Estimate"}, {"coefficient_of_variation_percent", "Coefficient ofvariation (%) ofestimate6"}, {"standard_error", "Standard error ofestimate"}, {"lower_bound_95_ci", "Lower bound (95%CI) of estimate"}, {"upper_bound_95_ci", "Upper bound (95%CI) of estimate"}, {"reference_date", "Date"}, {"year", "Year"}, {"month", "Month"}, {"source_sheet", "Source Sheet"}, {"source_table", "Source Table"}, {"table_title", "Table Title"}, {"series_type", "Series Type"}, {"frequency", "Frequency"}, {"noc_detail", "NOC Detail"}, {"noc_code", "NOC Code"}, {"noc_title", "NOC Title"}, {"is_suppressed", "Is Suppressed"}}),
				    #"Inserted Month Name" = Table.AddColumn(#"Renamed Columns", "Month Name", each Date.MonthName([Date]), type text)
				in
				    #"Inserted Month Name"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

